### ISSUE TITLE
Xcode build

### ISSUE THREAD

**Issue by sparfenyuk** [sourcey/libsourcey#1]
Hi!

I've just experienced some troubles to compile libsourcey project using Xcode. It seems that cmake doesn't properly link targets between each other. For example, to build 'stun' target I manually put some lines to linker options (see screenshot). And that is the problem for other targets too.

![image](https://cloud.githubusercontent.com/assets/134065/2914162/e722858c-d696-11e3-9940-06f5256d0785.png)

**Comment by auscaster** [comment]
Xcode build has been fixed on master.
