### ISSUE TITLE
Documentation on http://sourcey.com/libsourcey is unavailable

### ISSUE THREAD

**Issue by rusxg** [sourcey/libsourcey#102]
All the links that I've tried give 404 error. For example:
http://sourcey.com/libsourcey/api-archo.html
http://sourcey.com/libsourcey/api-base.html
http://sourcey.com/libsourcey/examples.html
http://sourcey.com/libsourcey/api-crypto.html
http://sourcey.com/libsourcey/api-http.html

**Comment by VinciShark** [comment]
@rusxg libsourcey's document is just renew these days.  Just wait days or so sonner.

**Comment by auscaster** [comment]
Hi thanks for the bug report, should be all sorted now:
http://sourcey.com/libsourcey/

Please close this off if it works for you

**Comment by rusxg** [comment]
Yes, it works now. Thanks!
