### ISSUE TITLE
size_t not defined in libsourcey/.../byteorder.h?

### ISSUE THREAD

**Issue by normano** [sourcey/libsourcey#103]
Trying to figure out what is going on with this error. Does this have to do something with the code?

cmake -DOPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2j/include/ -DCXX_STANDARD=11 -DCXX_STANDARD_REQUIRED=ON -DCMAKE_BUILD_TYPE=RELEASE ..

[ 33%] Building CXX object src/base/CMakeFiles/base.dir/src/buffer.cpp.o
In file included from /Users/norm/projects/libsourcey/src/base/src/buffer.cpp:12:
In file included from /Users/norm/projects/libsourcey/src/base/include/scy/buffer.h:16:
/Users/norm/projects/libsourcey/src/base/include/scy/byteorder.h:37:37: error: no type named 'size_t' in namespace 'std'
inline void set8(void* memory, std::size_t offset, std::uint8_t v)
                               ~~~~~^
/Users/norm/projects/libsourcey/src/base/include/scy/byteorder.h:42:51: error: no type named 'size_t' in namespace 'std'
inline std::uint8_t get8(const void* memory, std::size_t offset)
                                             ~~~~~^
In file included from /Users/norm/projects/libsourcey/src/base/src/buffer.cpp:12:
In file included from /Users/norm/projects/libsourcey/src/base/include/scy/buffer.h:17:
In file included from /Users/norm/projects/libsourcey/src/base/include/scy/memory.h:16:
In file included from /Users/norm/projects/libsourcey/src/base/include/scy/logger.h:20:
/Users/norm/projects/libsourcey/src/base/include/scy/thread.h:47:56: warning: base class 'scy::Runner' is uninitialized when used here to access
      'scy::Runner::_context' [-Wuninitialized]
        _thread(internal::runAsync<Function, Args...>, _context,
                                                       ^
1 warning and 2 errors generated.
make[2]: *** [src/base/CMakeFiles/base.dir/src/buffer.cpp.o] Error 1
make[1]: *** [src/base/CMakeFiles/base.dir/all] Error 2
make: *** [all] Error 2

Platform:
Host:                        Darwin 16.1.0 x86_64
CMake:                       3.7.1
CMake generator:             Unix Makefiles
CMake build tool:            /usr/bin/make
Configuration:               RELEASE

--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--     C++ flags (Release):         -std=c++11 -stdlib=libc++  -O3 -DNDEBUG  
--     C++ flags (Debug):           -std=c++11 -stdlib=libc++  -g 
--     C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
--     C flags (Release):           -O3 -DNDEBUG 
--     C flags (Debug):             -g 
--     Linker flags (Release):
--     Linker flags (Debug):

Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by auscaster** [comment]
Hi Norm

We just underwent a big overhaul for c++14 updates and removed a lot of old includes. The code was compiling on linux, but Apple seems to require an extra include. I just pushed a fix, please sync and close this one if all good :)

**Comment by normano** [comment]
Also appears to need #include <string> in Configuration.h and #include <ostream> in av/Src/avfoundation.cpp

**Comment by auscaster** [comment]
Hmm ... any chance you could push a PR through please? I don't have a mac to test on right now

**Comment by normano** [comment]
Probably just better off doing this on Windows or Linux.

In Sources/av/Src/avfoundation.mm, QTKit/QTKit.h cannot be found since apple removed qtkit in MacOS: https://github.com/opencv/opencv/issues/6913.

You can close the issue if you want. I'm going to do it on Windows.

**Comment by auscaster** [comment]
I just removed the old QTKit code, thanks for the heads up.

**Comment by auscaster** [comment]
On linux it works without the extra includes. Gotta love the std library inconsistencies! Thanks for the PR btw. If compilation works for you now please close this one off

**Comment by normano** [comment]
Last PR. Thanks!

**Comment by auscaster** [comment]
Thanks again, let me know if I can be of any help working with libsourcey.
