### ISSUE TITLE
TURNMediaProvider  in  exmaple

### ISSUE THREAD

**Issue by notedit** [sourcey/libsourcey#107]
i see the TURNMediaProvider exmaple in turn example.

it seems that  use this TURNMediaProvider  and  generate some ice candidate  to some other webrtc peer,  then i can have a true real time broadcast  system?

**Comment by auscaster** [comment]
The this would be possible, but you would need to code it. I'm closing this issue because it's not technically an issue, but if you have specific questions perhaps I can answer them

**Comment by notedit** [comment]
thansks,  i  will email you later.

**Comment by notedit** [comment]
hi  @auscaster   i  want to test  TURNMediaProvider  example.

can you give me  some advise  how can i make this work and another   webrtc client can  watch this

**Comment by auscaster** [comment]
Hi there, you can raise a TURN server (turn/samples/turnserver) and set the server URL on the WebRTC client in browser or native to use it.

**Comment by notedit** [comment]
what i understand is that  TURNMediaProvider  is a turn client and media provider,   another   peer  can connect to it and watch the media.   what i don't understand is that  how i can handler the sdp stuff?  answer/offer and sigaling

**Comment by auscaster** [comment]
OK I follow you ... this would require some hacking to work with webrtc
since the TURNMediaProvider does not implement any ICE signalling, only TURN
signalling.

If you want to stream media to a webrtc client there is a native
sample that does exactly that in `webrtc/samples/webrtcstreamer`
