### ISSUE TITLE
pointer to ICE implementation needed

### ISSUE THREAD

**Issue by muellni** [sourcey/libsourcey#109]
The Readme mentions 
> Full ICE stack ... based on LibSourcey architecture

While this library looks great ([I try to replace libnice](https://github.com/FAForever/ice-adapter)) I can't spot an ICE agent or similar in the sources. I found `webrtc/include/scy/webrtc/peerconnection.h` which seems to be based on webrtc (which I still need to install).
Where do I have to look?

**Comment by auscaster** [comment]
Hello, yes you are currect, WebRTC needs to be installed. Check the guides here for installing WebRTC with LibSourcey: https://github.com/sourcey/libsourcey/blob/master/doc/installation-linux.md#install-webrtc-optional

**Comment by muellni** [comment]
alright, but it this ICE implementation based on your stack (libuv networking, STUN and TURN) or on webrtc?

**Comment by auscaster** [comment]
There used to be an ICE agent but it is outdated, and we currently use WebRTC for ICE signalling. However, STUN and TURN are based on the LibSourcey stack. If you want a project I can give you the code to reimplement, but it might be a bit of a job.

**Comment by muellni** [comment]
Thank you for the explanation. I'll try the WebRTC signalling once I get it compiled. 
If you could point me at the outdated ICE agent code, I'd like to look at it.
