### ISSUE TITLE
forget to put SCY_EXTERN before class name

### ISSUE THREAD

**Issue by WeissGotsman** [sourcey/libsourcey#111]
#ifdef SCY_WIN
#ifndef SCY_SHARED_LIBRARY // libsourcey.h
#define SCY_EXTERN __declspec(dllexport)
#else
#define SCY_EXTERN __declspec(dllimport)
#endif
#else
#define SCY_EXTERN // nothing
#endif

glad to see these are defined, but forget to put SCY_EXTERN in front of the class name, so the built dll does not export any symbols (check with dependency walker) and does not work in windows, please fix

**Comment by auscaster** [comment]
Fixed in d8c004ee078864cfa9727f33f192f39162ee3be1
