### ISSUE TITLE
ideas on webrtc sfu  based on libsourcey

### ISSUE THREAD

**Issue by notedit** [sourcey/libsourcey#116]
i see the webrtc module,  it is  convenient to do  one to one webrtc connection.

any ideas on sfu server based on libsourcey webrtc module.

**Comment by auscaster** [comment]
Yes the libsourcey webrtc module is perfect for one to one or one or many. IT also includes classes for streaming and recording media files.

I would love to include a SFU server into LibSourcey, but don't have any plans for it at the time. If you're interested in having a go I would be happy to give you any support you need.

**Comment by notedit** [comment]
ok   i will digg much in my free time.   close this for now.
