### ISSUE TITLE
CMake error with FindWebRTC.cmake

### ISSUE THREAD

**Issue by webbery** [sourcey/libsourcey#118]
Hi,
after #115 resolved, I pull the latest code. But it seems that release version of cmake have some prombles. I get the following error:
`CMake Error at cmake/FindWebRTC.cmake:114 (get_filename_component):`
`  get_filename_component called with incorrect number of arguments`
`Call Stack (most recent call first):`
`  cmake/LibSourceyIncludes.cmake:47 (find_package)`
`  cmake/LibSourceyIncludes.cmake:90 (find_dependency)`
`  src/webrtc/CMakeLists.txt:4 (include_dependency)`
and  `Release` of `WEBRTC Variables` looks like disk name is missing:
`-- Release Libraries: /Program Files (x86)/Microsoft Visual Studio 12.0/VC/lib/amd64/vccorlibd.lib;/Program Files (x86)/Microsoft Visual Studio 12.0/VC/lib/amd64/vcomp.lib;...`
So I think somewhere still have bugs?

**Comment by auscaster** [comment]
Hi @webbery, sorry for the confusion! Can you please let me know if `master` is working for you now?

**Comment by fibasile** [comment]
Hi, I was compiling fine with the old version of FindWebRTC.cmake on linux passing 
-DWEBRTC_INCLUDE_DIR=/src/webrtcbuilds/out/src to cmake. Which setting should I pass with this version?

**Comment by auscaster** [comment]
It has been changed to `WEBRTC_ROOT_DIR` for consistency with other CMake finders.

**Comment by webbery** [comment]
Hi @fibasile , I pulled the latest version of today's on master. It seemed that #115 apears again. 
My WebRTC folder structure is:
~~~~
E:\WebRTC-Win\webrtc
|----src
|        |----out
|        |        |----Debug       <-------I copy all libs to here from  -- |
|        |        |        |---- obj                                                             |
|        |        |                 |---- webrtc                                               |
|        |        |                          |---- webrtc.lib     -------------------|
|        |        |----Debug_x64
|        |        |----Release
|        |        |----Release_x64
|        |----webrtc
|        |----third_party
|        |----all.sln
        ...
|----tools
|----third_party
...
~~~~

**Comment by auscaster** [comment]
Hi @webbery, there should be no need to copy any .lib files inside the obj folder. The build script globs everything and adds it to the project. With your current directory structure you should just need to set `WEBRTC_ROOT_DIR`

**Comment by auscaster** [comment]
Just in case it can be of assistance this is the build command that I use to build LibSOurcey with WebRTC on a windows system: 

```
cmake -G "Visual Studio 14 Win64" .. -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_SHARED_LIBS=OFF -DBUILD_MODULES=OFF -DBUILD_APPLICATIONS=OFF -DBUILD_SAMPLES=ON -DBUILD_TESTS=ON -DWITH_WEBRTC=ON -DWITH_FFMPEG=ON -DBUILD_MODULE_base=ON -DBUILD_MODULE_crypto=ON -DBUILD_MODULE_http=ON -DBUILD_MODULE_json=ON -DBUILD_MODULE_av=ON -DBUILD_MODULE_net=ON -DBUILD_MODULE_socketio=ON -DBUILD_MODULE_symple=ON -DBUILD_MODULE_util=ON -DBUILD_MODULE_uv=ON -DBUILD_MODULE_stun=ON -DBUILD_MODULE_turn=ON -DBUILD_MODULE_webrtc=ON -DOPENSSL_ROOT_DIR=E:\dev\vendor\OpenSSL-Win64 -DFFMPEG_ROOT_DIR=E:\dev\vendor\ffmpeg-3.2.2-win64-dev -DWEBRTC_ROOT_DIR=E:\dev\vendor\webrtc-checkout\src
```

**Comment by webbery** [comment]
Hi @auscaster, thx! It works! But why `WEBRTC_ROOT_DIR` is not a folder selector in CMake GUI? I though it might be ignore.

**Comment by auscaster** [comment]
It's not marked as an advanced variable so it should be visible ... Perhaps you need to regenerate your cmake cache?

**Comment by webbery** [comment]
Perhaps, now I'm compilling the code. Hopes it works well! thanks very much!

**Comment by auscaster** [comment]
If you are compiling from default WebRTC libs on windows you may experience an issue with multiple defined `jsoncpp` symbols. The issue and a solution is explained here: https://github.com/sourcey/libsourcey/issues/119

I'm actually working on a permanent fix today - hope you can wait for a few hours if you are hit by this.

**Comment by webbery** [comment]
I think I should find a VPN to cross the Great Firewall first and download the latest version of webrtc from google. Because some types of webrtc are not found.

**Comment by auscaster** [comment]
Yes, a VPN is a must for every Chinese software developer :)

The WebRTC sources change fast, so its good to work from the official repo.

**Comment by auscaster** [comment]
Please close this if fixed
