### ISSUE TITLE
Unable to build WebRTC using webrtcbuilds on win64 system

### ISSUE THREAD

**Issue by DanAndersen** [sourcey/libsourcey#120]
Hi,
I have been attempting unsuccessfully to get WebRTC (using the script at https://github.com/sourcey/webrtcbuilds ) on a Win64 system. I am attempting to follow the build command that was said to work in https://github.com/sourcey/libsourcey/issues/119 .

First, I hit an "Unresolved dependencies" error:
```
$ ./build.sh -l jsoncpp -e ENABLE_RTTI
Host OS: win
Target OS: win
Target CPU: x64
Checking webrtcbuilds dependencies
Checking depot-tools
Building revision: 78d89778b435854e9c25d0b0ae489b13da28436e
Associated revision number: 17015
Checking out WebRTC revision (this will take awhile): 78d89778b435854e9c25d0b0ae489b13da28436e
[...]
Checking WebRTC dependencies
Patching WebRTC source
Compiling WebRTC
Generating project files with: rtc_include_tests=false enable_iterator_debugging=false target_os="win" target_cpu="x64"
ERROR Unresolved dependencies.
//:default(//build/toolchain/win:x64)
  needs //webrtc:webrtc(//build/toolchain/win:x64)
```

Based on https://github.com/vsimon/webrtcbuilds/issues/39, I followed a suggestion to manually change
`local common_args="rtc_include_tests=false enable_iterator_debugging=false" #is_component_build=false"`
to
`local common_args="rtc_include_tests=true enable_iterator_debugging=false" #is_component_build=false"`
in `util.sh`. This gets me past the unresolved dependency error, but then I end up with a linker warning being treated as an error and stopping the compilation process early.

```
$ ./build.sh -l jsoncpp -e ENABLE_RTTI
Host OS: win
Target OS: win
Target CPU: x64
Checking webrtcbuilds dependencies
Checking depot-tools
Building revision: a1991c517598fda9c9c0cf8876886e3968436ff9
Associated revision number: 17016
Checking out WebRTC revision (this will take awhile): a1991c517598fda9c9c0cf8876886e3968436ff9
[...]
[51/389] LINK audio_device_tests.exe audio_device_tests.exe.pdb
FAILED: audio_device_tests.exe audio_device_tests.exe.pdb
E:/webrtc/001/webrtcbuilds/depot_tools/python276_bin/python.exe ../../build/toolchain/win/tool_wrapper.py link-wrapper environment.x64 False link.exe /nologo /OUT:./audio_device_tests.exe /PDB:./audio_device_tests.exe.pdb @./audio_device_tests.exe.rsp
uuid.lib(unknwn_i.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification
LINK : error LNK1218: warning treated as error; no output file generated
[...]
ninja: build stopped: subcommand failed.
```

It's unclear to me even what this error means or how to resolve it. Do you have a known working set of build instructions for a particular webrtc revision/release, or can you please help me figure out what to do next to get this built? I have been struggling with getting libsourcey built for several days now. Thank you!

**Comment by fibasile** [comment]
I was struggling with the same problem, now tried with another branch for rtc, 3355f6d, builds well but now having problems with boringssl when linking webrtcrecorder :(

**Comment by fibasile** [comment]
So branch-heads 54 is the latest that builds without the rtc_include_tests=true, but libsourcey won't compile with it. 

Please tell us which branch-head to compile for allowing webrtcrecorder to work.

**Comment by radioman** [comment]
if you look for windows solution, check https://github.com/radioman/WebRtc.NET

**Comment by auscaster** [comment]
Hi guys, sorry for the late response and that you are having trouble with WebRTC - it can be a royal pain in the ass. 

On windows I have been compiling webrtc from master branch (branch-heads-57). This guide is super helpful: https://github.com/ipop-project/ipop-project.github.io/wiki/Building-the-WebRTC-lib-for-Windows

On linux I use `webrtcbuilds` but its been a month or so since I compiled. I will checkout the latest master branch and try it out again today.

**Comment by auscaster** [comment]
@fibasile how did you get on? Feel free to skype me on @auscaster if you want to chat.

**Comment by auscaster** [comment]
I've been digging into compiling WebRTC master on Win64 and there is a conflict between BoringSSL and OpenSSL. The answer is to compile WebRTC with OpenSSL instead of BoringSSL. Am still working on  the specifics, and will report back when I have it working.

**Comment by auscaster** [comment]
As promised the latest the OpenSSL / BoringSSL conflicts have been resolved on master. The solution was to compile with BoringSSL instead of OpenSSL when WebRTC is being used - it was the only safe way to resolve the issue.
