### ISSUE TITLE
WebRTC compile errors

### ISSUE THREAD

**Issue by RichLewis007** [sourcey/libsourcey#125]
Hi, I'm following your instructions on building your version of WebRTC on macOS. (I believe I need to do this in order to compile libsourcey with WebRTC capability.) It worked for a while, then stopped with this error:

Checking WebRTC dependencies
Patching WebRTC source
Compiling WebRTC
Generating project files with: rtc_include_tests=false enable_iterator_debugging=false target_os="mac" target_cpu="x64"
ERROR Unresolved dependencies.
//:default(//build/toolchain/mac:clang_x64)
  needs //webrtc:webrtc(//build/toolchain/mac:clang_x64)

FYI, I wasn't able to get the build.sh program to run as written in the instructions, but this seemed to work after I put a -d at the end:

`./build.sh -l jsoncpp -e -d`

Do you know what that error of unresolved dependencies refers to?

Thanks!

**Comment by auscaster** [comment]
It was written for Linux so your best best would be to compile webrtc manually, or maybe update the webrtcbuilds .sh scripts ... I'm sure they wont need much tweaking to work on mac.

**Comment by auscaster** [comment]
Closing due to no further comment.

**Comment by pims** [comment]
I'm running into the same issue on Linux:

```
ubuntu@ip-10-0-3-168:~/webrtc-builds$ ./build.sh -d
./build.sh: line 41: OPTARG: unbound variable
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

Which version of bash are you using?

```
bash --version
GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)
```

**Comment by AdoPi** [comment]
Even in zsh, I have the same problem

> zsh 5.0.7 (x86_64-pc-linux-gnu)

**Comment by RichLewis007** [comment]
I'm using:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by auscaster** [comment]
Hello all, the latest webrtc-build repo has been fixed.

**Comment by AdoPi** [comment]
Hi, which revision of webrtc are you using for compiling libsourcey?
