### ISSUE TITLE
Latest commit broke webrtcstreamer - streamingpeerconnection.h now deprecated

### ISSUE THREAD

**Issue by DanAndersen** [sourcey/libsourcey#129]
In the latest updates, streamingpeerconnection.h was moved into the deprecated directory, but webrtcstreamer still depends on it, leading to a compile error. Does the CMake script have an option to include the deprecated code into the built project?

**Comment by auscaster** [comment]
I think you may be using outdated webrtcstreamer code. The streamingpeerconnection was removed in favor of a simpler implementation.

**Comment by auscaster** [comment]
Hey Dan, just checking if you got the sample working? Let me know if you need a hand with anything.

**Comment by DanAndersen** [comment]
Hi,
Thanks for following up; I hadn't had time to look further until now. Looks like the compile issue is still there but it's just due to the fact that the line `#include "scy/webrtc/streamingpeerconnection.h"` is still in signaler.cpp. 

Commenting out that line lets me build it and run with no apparent issues (the audio is skipping on the test file, but I'll investigate that to see if there's something on my end that is causing it).

**Comment by auscaster** [comment]
OK thanks!

Audio skipping? I can safely say it works in proper realtime on my system.
Perhaps performance is an issue?
