### ISSUE TITLE
How to build the library and samples

### ISSUE THREAD

**Issue by sibirchakraborty** [sourcey/libsourcey#130]
How to build the library and samples

**Comment by auscaster** [comment]
Check the docs: http://sourcey.com/libsourcey/

**Comment by sibirchakraborty** [comment]
In Fedora compile failing

**Comment by sibirchakraborty** [comment]
Asking for 4.9 and above gcc

**Comment by auscaster** [comment]
The code uses C++14 so you need to upgrade gcc to >= 4.9
