### ISSUE TITLE
WebRTC troubles

### ISSUE THREAD

**Issue by cexcell** [sourcey/libsourcey#132]
Hi! That's not actually an issue, but could you please provide an external repo or just some archive with Debug and Release WebRTC binaries(Visual Studio 2015) that libsourcey could be linked with?
Thanks!

**Comment by auscaster** [comment]
Hmm it's not a bad idea, but I can imagine it would be difficult to maintain.

I did something similar for a user a while back and provided some static libraries for him. The libs are still on dropbox: https://github.com/sourcey/libsourcey/issues/123

**Comment by cexcell** [comment]
For Debug version it works fine, but for release it fails with "Error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in main.obj"

**Comment by auscaster** [comment]
Yes it's just for debug.

**Comment by cexcell** [comment]
@auscaster yep, my bad. Maybe last question: what flags did you use in "gn gen ..."?
[These ones](https://github.com/sourcey/libsourcey/blob/master/doc/installation-windows.md#install-webrtc-optional) or something else? Because in my case output directory contains only static libraries without dlls.

**Comment by auscaster** [comment]
I used the exact steps from here: https://github.com/sourcey/libsourcey/blob/master/doc/installation-windows.md#install-webrtc-optional

**Comment by cexcell** [comment]
@auscaster Thanks. Building such c++ projects for windows is quite a headache

**Comment by auscaster** [comment]
Yeah and WebRTC is one of the worst! I've actually been giving some though
to providing precompiled WebRTC lib for Windows as you suggested, and might
go ahead with it. The only catch is people still need to download the 8
gigs of WebRTC library, so I'm not sure that there would be any great
benefit.

**Comment by auscaster** [comment]
Incase you're still interested I decided to start making precompiled libraries for WebRTC. You're not the first one to ask for it! 

https://sourcey.com/precompiled-webrtc-for-windows/

**Comment by cexcell** [comment]
@auscaster Thanks again! It helps a lot :-)

**Comment by pims** [comment]
@auscaster do you think this would be possible to do the same for Linux 😁 
Unfortunately running into build issues with webrtc as well 😞

**Comment by auscaster** [comment]
Hi @pims I will certainly consider it.
