### ISSUE TITLE
Example of executing async process in http request handler

### ISSUE THREAD

**Issue by diorahman** [sourcey/libsourcey#133]
Hi,

Could you help us on providing example, e.g. consuming external service asynchronously (hence non-blocking) inside the request handler? e.g. in here https://github.com/sourcey/libsourcey/blob/master/src/http/samples/httpechoserver/httpechoserver.h#L38
?

Thanks!

**Comment by auscaster** [comment]
Hi there, sorry for the delay.

The code in the `mediaserver` demo has anb example of using a `http::ServerConnectionFactory` and `http::ServerResponder` to acheive exactly this.

https://github.com/sourcey/libsourcey/blob/master/src/av/samples/mediaserver/mediaserver.h
