### ISSUE TITLE
Compile on Linux with SAMPLES_webrtc

### ISSUE THREAD

**Issue by VladislavSu** [sourcey/libsourcey#138]
Hello,

I try to cmake with this command:
(if building on the current master checkout)

`cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DWITH_WEBRTC=ON -DBUILD_SAMPLES_webrtc=ON -DWITH_FFMPEG=ON \
-DWEBRTC_ROOT_DIR=~/tmp/webrtcbuilds/out/webrtcbuilds-17821-fd68d65-linux-x64/ 
-DBUILD_SHARED_LIBS=OFF`

After running 

`make`

I got Error:

```
Linking CXX executable stuntests
~/tmp/webrtcbuilds/out/webrtcbuilds-17821-fd68d65-linux-x64/lib/x64/Release/libwebrtc_full.a: error adding symbols: Malformed archive
```

If I used previous commit I got

```
Linking CXX executable stuntests
/usr/bin/ld: ~/tmp/webrtcbuilds/out/src/out/x64/Release/obj/third_party/boringssl/boringssl/cpu-intel.o: unrecognized relocation (0x2a) in section `.text.OPENSSL_cpuid_setup'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [stun/tests/stuntests] Error 1
make[1]: *** [stun/tests/CMakeFiles/stuntests.dir/all] Error 2
make: *** [all] Error 2
```

May be something wrong with my libc6?

```
dpkg -l | grep libc6
ii  libc6:amd64                           2.19-0ubuntu6.11                      amd64        Embedded GNU C Library: Shared libraries
ii  libc6-dev:amd64                       2.19-0ubuntu6.11                      amd64        Embedded GNU C Library: Development Libraries and Header Files
ii  libc6-i386                            2.19-0ubuntu6.11                      amd64        Embedded GNU C Library: 32-bit shared libraries for AMD64
```
 
Thanks for any help.

**Comment by auscaster** [comment]
Hi there, 

WebRTC can be difficult to build! There have been some updated to out internal build scripts that now use clang as the default compiler. Please try again with these scripts: https://github.com/sourcey/webrtc-builds

**Comment by auscaster** [comment]
Any update on this?

**Comment by VladislavSu** [comment]
Thank you for response.
Sorry for delay.
I've compiled and build WebRTC successfully.
However when I try make libsourcey I got linking errors.
I'll try new version of scripts on this weekend.

**Comment by auscaster** [comment]
I recommend using these precompiled libraries here as they work well: https://github.com/sourcey/webrtc-precompiled-builds/raw/master/webrtc-17657-02ba69d-linux-x64.tar.gz

If that goes well then maybe try linking your own.

**Comment by VladislavSu** [comment]
Thank you for recommendation. I've downloaded and unzip it (https://github.com/sourcey/webrtc-precompiled-builds/raw/master/webrtc-17657-02ba69d-linux-x64.tar.gz) to 'webrtc-17657-02ba69d-linux-x64' directory.

And used cmake:
`cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DWITH_WEBRTC=ON -DBUILD_SAMPLES_webrtc=ON -DWITH_FFMPEG=ON \
-DWEBRTC_ROOT_DIR=/home/vagrant/tmp/webrtcbuilds/webrtc-17657-02ba69d-linux-x64 \
-DBUILD_SHARED_LIBS=OFF`

And got error
`-- Could NOT find WEBRTC (missing:  WEBRTC_LIBRARIES) 
CMake Error at cmake/LibSourceyIncludes.cmake:72 (message):
  Failed to include dependency: WebRTC.  Please build and install
  dependencies before using CMake.
Call Stack (most recent call first):
  LibSourcey.cmake:243 (find_dependency)
  CMakeLists.txt:35 (include)
`

Did I unzip it to a wrong place?
Or may be because it doesn't contain 'out' directory?

**Comment by auscaster** [comment]
Sorry it was broken on a recent commit. Please sync and all should work properly

**Comment by VladislavSu** [comment]
Thank you for your help.
cmake how works successful.

But during building I got new error:

`Building CXX object base/CMakeFiles/base.dir/src/pipe.cpp.o
In file included from /home/vagrant/tmp/libsourcey/src/base/include/scy/stream.h:18:0,
                 from /home/vagrant/tmp/libsourcey/src/base/include/scy/pipe.h:17,
                 from /home/vagrant/tmp/libsourcey/src/base/src/pipe.cpp:12:
/home/vagrant/tmp/libsourcey/src/base/include/scy/request.h: In static member function ‘static void scy::uv::GetAddrInfoReq::getAddrInfoCallback(scy::uv::Request<uv_getaddrinfo_s, scy::uv::GetAddrInfoEvent>::Type*, int, addrinfo*)’:
/home/vagrant/tmp/libsourcey/src/base/include/scy/request.h:137:56: error: no matching function for call to ‘scy::uv::GetAddrInfoEvent::GetAddrInfoEvent(<brace-enclosed initializer list>)’
             wrap->callback(GetAddrInfoEvent{status, res});
`

**Comment by auscaster** [comment]
Compiler?

**Comment by VladislavSu** [comment]
Yes.

**Comment by auscaster** [comment]
Sorry, which compiler are you using? If you're on linux you will need gcc
>= 5

**Comment by VladislavSu** [comment]
After updating gcc to version 5.4.1 everything works fine.
Thank you.
