### ISSUE TITLE
I want to develop a webrtc app with ffmpeg.I think sourcey is good want to join in.But I find I can not build the webrtc right!when run webrtc build test example

### ISSUE THREAD

**Issue by colorlength** [sourcey/libsourcey#139]
I can not 

/tmp/cch5Lp9i.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > cricket::VectorToString<cricket::AudioCodec>(std::vector<cricket::AudioCodec, std::allocator<cricket::AudioCodec> > const&)':
simple_app.cc:(.text+0x8df): undefined reference to `cricket::AudioCodec::ToString[abi:cxx11]() const'
/tmp/cch5Lp9i.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > cricket::VectorToString<webrtc::RtpExtension>(std::vector<webrtc::RtpExtension, std::allocator<webrtc::RtpExtension> > const&)':
simple_app.cc:(.text+0xa73): undefined reference to `webrtc::RtpExtension::ToString[abi:cxx11]() const'
/tmp/cch5Lp9i.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > cricket::VectorToString<cricket::DataCodec>(std::vector<cricket::DataCodec, std::allocator<cricket::DataCodec> > const&)':
simple_app.cc:(.text+0xc07): undefined reference to `cricket::DataCodec::ToString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status

**Comment by auscaster** [comment]
I have seen this before when building with newer versions of GCC built
without 4.8 backwards compatibility.
Please add -D_GLIBCXX_USE_CXX11_ABI=0 to the compiler flags in run_tests.sh
and it should compile, you may also need to add the flag when compiling
LibSourcey ... let me know how you go :)

**Comment by colorlength** [comment]
thank u! thank u! i can run it on ubuntu16.04 with gcc 5.4.

**Comment by auscaster** [comment]
Awesome :)
