### ISSUE TITLE
Issue trying to build webrtc samples

### ISSUE THREAD

**Issue by adam-denny** [sourcey/libsourcey#144]
I'm trying to build the webrtc samples, and after managing to get the webrtc build finishing I'm getting several strange errors, example: 

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/adam/tmp/libsourcey/src/archo/OPENSSL_INCLUDE_DIR
   used as include directory in directory /home/adam/tmp/libsourcey/src/archo
/home/adam/tmp/libsourcey/src/archo/tests/OPENSSL_INCLUDE_DIR
   used as include directory in directory /home/adam/tmp/libsourcey/src/archo/tests
/home/adam/tmp/libsourcey/src/av/OPENSSL_INCLUDE_DIR
   used as include directory in directory /home/adam/tmp/libsourcey/src/av
/home/adam/tmp/libsourcey/src/av/tests/OPENSSL_INCLUDE_DIR
   used as include directory in directory /home/adam/tmp/libsourcey/src/av/tests
/home/adam/tmp/libsourcey/src/base/OPENSSL_INCLUDE_DIR
   used as include directory in directory /home/adam/tmp/libsourcey/src/base
/home/adam/tmp/libsourcey/src/base/tests/OPENSSL_INCLUDE_DIR
   used as include directory in directory /home/adam/tmp/libsourcey/src/base/tests
/home/adam/tmp/libsourcey/src/crypto/OPENSSL_INCLUDE_DIR
   used as include directory in directory /home/adam/tmp/libsourcey/src/crypto
/home/adam/tmp/libsourcey/src/crypto/tests/OPENSSL_INCLUDE_DIR
...
`

it goes on through a good 30 more. I'm not super experienced with cmake, but it looks like it's trying to access the variable OPENSSL_INCLUDE_DIR as a string itself rather than a directory string. 

Here's the cmake command I'm trying to execute: 

`cmake -DCMAKE_BUILD_TYPE=DEBUG -DWITH_WEBRTC=ON -DBUILD_SAMPLES_webrtc=ON .. `

I did change a line in FindWebRTC.cmake to point directly to a webrtc build because the script was having trouble finding it, which was successful, but now I'm stuck here and no matter what I try I can't seem to get this sorted out. Thanks in advance!

**Comment by auscaster** [comment]
Hmm... try using the [circle.yml](https://github.com/sourcey/libsourcey/blob/master/circle.yml) file as a guide. 

Also try removing your old `build` directory as cache may be stale.

**Comment by auscaster** [comment]
Hi Adam did you figure this out? The build system is being constantly updated, would you be able to try again with the latest master or close this please?
