### ISSUE TITLE
Is it possible to organize 'video on demand' with seeking?

### ISSUE THREAD

**Issue by artemiuzzz** [sourcey/libsourcey#151]
Looking a way to implement such feature, is it possible with libsourcey?

**Comment by auscaster** [comment]
Yes you could use the https://github.com/sourcey/libsourcey/tree/master/src/av/samples/mediaserver or WebRTC. Neither of those have seeking inbuild, so you would have to implement it yourself, but its not hard with the FFmpeg layer.
