### ISSUE TITLE
Sched module build issue : export symbol used but not defined

### ISSUE THREAD

**Issue by Malesio** [sourcey/libsourcey#153]
Hi Kam,

In commit https://github.com/sourcey/libsourcey/commit/f9157179e3adefcf4aafe356a60c654eb178ea78, you've uncommented the `Sched_API` export symbol. However, it isn't defined anywhere. I'd suggest to create a `sched.h` file in `src/sched/include/scy/sched` directory, with the same content as similar files, like `http.h` in `src/http/include/scy/http`. You'd also want to include this file in `task.h`, since `task.h` is included by everything in `sched` module.

Suggested content (that makes my compiler happy) :
```cpp
///
//
// LibSourcey
// Copyright (c) 2005, Sourcey <https://sourcey.com>
//
// SPDX-License-Identifier: LGPL-2.1+
//
/// @addtogroup http
/// @{


#ifndef SCY_Sched_h
#define SCY_Sched_h


#include "scy/base.h"


// Shared library exports
#if defined(SCY_WIN) && defined(SCY_SHARED_LIBRARY)
    #if defined(Sched_EXPORTS)
        #define Sched_API __declspec(dllexport)
    #else
        #define Sched_API __declspec(dllimport)
    #endif
#else
    #define Sched_API // nothing
#endif


#endif // SCY_Sched_H


/// @\}
``` 
(I got lazy making a new pull request, 'cause I've already made some changes about `httptests` and `nettests` segfault issue).

Thanks for providing and supporting such a great lib!

**Comment by auscaster** [comment]
OK thanks for the heads up.

Let me know if you fix any issues with the demos.
