### ISSUE TITLE
webrtcstreamer sample churns CPU

### ISSUE THREAD

**Issue by michaelfig** [sourcey/libsourcey#156]
Hi,

I'm working on getting the webrtcstreamer sample set up, and I noticed that when I have my Symple server running, but no clients connected, the webrtcstreamer program gradually uses more and more CPU (starting at around 7%, but after 10 minutes or so, hitting 37%).

Stracing the webrtcstreamer process shows a loop of:

```
select(23, [22], [], NULL, {0, 10000})  = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {64083, 162802086}) = 0
epoll_wait(6, [], 1024, 0)              = 0
clock_gettime(CLOCK_MONOTONIC, {64083, 162874180}) = 0
clock_gettime(CLOCK_MONOTONIC, {64083, 162914301}) = 0
clock_gettime(CLOCK_MONOTONIC, {64083, 162950361}) = 0
clock_gettime(CLOCK_MONOTONIC, {64083, 162970224}) = 0
gettimeofday({1496764575, 340729}, NULL) = 0
select(23, [22], [], NULL, {0, 10000})  = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {64083, 173276864}) = 0
epoll_wait(6, [], 1024, 0)              = 0
clock_gettime(CLOCK_MONOTONIC, {64083, 173346290}) = 0
clock_gettime(CLOCK_MONOTONIC, {64083, 173387245}) = 0
clock_gettime(CLOCK_MONOTONIC, {64083, 173460144}) = 0
clock_gettime(CLOCK_MONOTONIC, {64083, 173499379}) = 0
gettimeofday({1496764575, 351239}, NULL) = 0
select(23, [22], [], NULL, {0, 10000})  = 0 (Timeout)
```

(This is on Ubuntu xenial.)

Could this be a bad interaction between libuv and a webrtc event loop?

Thanks,
Michael.

**Comment by auscaster** [comment]
Hi Michael

My guess is that this is because the video decoder thread is started as soon as the sample is run, and continually loops the video. I'll have a closer look at this.

**Comment by auscaster** [comment]
It seems that this issue is Linux specific, as CPU is constant on Windows. At this point I suspect the issue is in the FFmpeg h.264 decoder when seeking is used to loop the stream.

**Comment by auscaster** [comment]
Since the stream was started right away there was an audio buffer filling up.

Now the media stream is started/stopped on peer connection and resting CPU is much lower.
