### ISSUE TITLE
Sourcey.com email timing out

### ISSUE THREAD

**Issue by fohara** [sourcey/libsourcey#158]
Hello, I realize this is likely not the most relevant place to mention this, but I wasn't sure where else I could pass it along. I tried to contact you via the email listed in your profile, but I got a couple bounces:

    The recipient server did not accept our requests to connect: [mail.sourcey.com. 74.207.248.97: timed out]

I was hoping to get your thoughts on a few integration points and figured email might be easier at the onset. Thanks.

**Comment by auscaster** [comment]
Thanks I'll get that looked at. For now I will close this issue and feel free to list your points here :)
