### ISSUE TITLE
CMake cannot find custom WebRTC build

### ISSUE THREAD

**Issue by artemiuzzz** [sourcey/libsourcey#160]
I built WebRTC in Gentoo with my own scripts, and trying to build with setting WEBRTC_ROOT_DIR, here it is:

```
cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=OFF \
-DBUILD_APPLICATIONS=OFF -DBUILD_MODULES=OFF \
-DBUILD_SAMPLES=OFF -DBUILD_TESTS=ON \
-DBUILD_MODULE_base=ON -DBUILD_MODULE_crypto=ON \
-DBUILD_MODULE_http=ON -DBUILD_MODULE_json=ON \
-DBUILD_MODULE_av=ON -DBUILD_MODULE_net=ON \
-DBUILD_MODULE_socketio=ON -DBUILD_MODULE_stun=ON \
-DBUILD_MODULE_symple=ON -DBUILD_MODULE_turn=ON \
-DBUILD_MODULE_util=ON -DBUILD_MODULE_webrtc=ON \
-DWITH_WEBRTC=ON -DWEBRTC_ROOT_DIR=/home/artem/webrtc-checkout/src \
-DWITH_FFMPEG=OFF -DWITH_OPENCV=OFF \
-DBUILD_MODULE_archo=OFF -DBUILD_MODULE_pacm=OFF \
-DBUILD_MODULE_pluga=OFF -DBUILD_MODULE_sked=OFF

...

-- Could NOT find WEBRTC (missing:  WEBRTC_LIBRARIES) 
CMake Error at cmake/LibSourceyIncludes.cmake:72 (message):
  Failed to include dependency: WebRTC.  Please build and install
  dependencies before using CMake.
Call Stack (most recent call first):
  LibSourcey.cmake:243 (find_dependency)
  CMakeLists.txt:35 (include)
...
```
Commit 23e72cfd6c3e8369494fbf344433c64ecc255fe7
CMake 3.5.2

And it seems that commenting this line helps:
https://github.com/sourcey/libsourcey/blob/master/cmake/FindWebRTC.cmake#L168

**Comment by auscaster** [comment]
Hi there

That's an interesting fix! Since I can't replicate the issue can you please try one thing for me on your end.
Move this block:

```
# HACK: WEBRTC_LIBRARIES and WEBRTC_DEPENDENCIES not propagating to parent scope
# while the WEBRTC_DEBUG_LIBRARY and WEBRTC_RELEASE_LIBRARY vars are.
# Setting PARENT_SCOPE fixes this solves theis issue for now.
set(WEBRTC_LIBRARIES ${WEBRTC_LIBRARIES} CACHE INTERNAL "")
set(WEBRTC_DEPENDENCIES ${WEBRTC_DEPENDENCIES} CACHE INTERNAL "")
set(WEBRTC_INCLUDE_DIRS ${WEBRTC_INCLUDE_DIRS} CACHE INTERNAL "")
set(WEBRTC_FOUND ${WEBRTC_FOUND} CACHE INTERNAL "")
```

to above the `select_library_configurations` call. It may be that CMake can't determine the presence of the WEBRTC_LIBRARIES variable unless it's fully cached.

Its worth noting that since you have commented out  `select_library_configurations` your build wont be able to distinguish between release and debug libraries.

Thanks!

**Comment by artemiuzzz** [comment]
I've tried to move the block before `select_library_configurations`, but it didn't help.

**Comment by auscaster** [comment]
OK thanks for trying.

Can I please trouble you to tell me the output from these variables:

```
message("WEBRTC_LIBRARIES_DEBUG: ${WEBRTC_LIBRARIES_DEBUG}")
message("WEBRTC_LIBRARIES_RELEASE: ${WEBRTC_LIBRARIES_RELEASE}")
message("WEBRTC_LIBRARIES: ${WEBRTC_LIBRARIES}")
```

**Comment by artemiuzzz** [comment]
Sure, I'll try it, but I'll have access to my Gentoo on Monday.

**Comment by artemiuzzz** [comment]
I've added messages after `select_library_configurations` and that is what I got:
```
cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=OFF -DBUILD_APPLICATIONS=OFF -DBUILD_MODULES=OFF -DBUILD_SAMPLES=OFF -DBUILD_TESTS=ON -DBUILD_MODULE_base=ON -DBUILD_MODULE_crypto=ON -DBUILD_MODULE_http=ON -DBUILD_MODULE_json=ON -DBUILD_MODULE_av=ON -DBUILD_MODULE_net=ON -DBUILD_MODULE_socketio=ON -DBUILD_MODULE_stun=ON -DBUILD_MODULE_symple=ON -DBUILD_MODULE_turn=ON -DBUILD_MODULE_util=ON -DBUILD_MODULE_webrtc=ON -DWITH_WEBRTC=ON -DWEBRTC_ROOT_DIR=/home/artem/webrtc-checkout/src -DWITH_FFMPEG=OFF -DWITH_OPENCV=OFF -DBUILD_MODULE_archo=OFF -DBUILD_MODULE_pacm=OFF -DBUILD_MODULE_pluga=OFF -DBUILD_MODULE_sked=OFF
-- Checking for one of the modules 'opencv'
-- - Linking dependency libuv with libraries: 
-- - Linking dependency minizip with libraries: 
-- - Linking dependency http_parser with libraries: 
WEBRTC_LIBRARIES_DEBUG: 
WEBRTC_LIBRARIES_RELEASE: /home/artem/webrtc-checkout/src/out/Release/obj/thirdparty/protobuf/libprotobuf_full.a;/home/artem/webrtc-checkout/src/out/Release/oj/third_party/boringssl/libboringssl.a;/home/artem/webrtc-checkout/src/out/Relese/obj/webrtc/system_wrappers/libmetrics_default.a;/home/artem/webrtc-checkout/rc/out/Release/obj/webrtc/system_wrappers/libfield_trial_default.a;/home/artem/ebrtc-checkout/src/out/Release/obj/webrtc/libwebrtc.a
WEBRTC_LIBRARIES: WEBRTC_LIBRARY-NOTFOUND
-- Could NOT find WEBRTC (missing:  WEBRTC_LIBRARIES) 
CMake Error at cmake/LibSourceyIncludes.cmake:72 (message):
  Failed to include dependency: WebRTC.  Please build and install
  dependencies before using CMake.
Call Stack (most recent call first):
  LibSourcey.cmake:243 (find_dependency)
  CMakeLists.txt:35 (include)


-- Configuring incomplete, errors occurred!
See also "/home/artem/libsourcey/build/CMakeFiles/CMakeOutput.log".
```

**Comment by auscaster** [comment]
OK thanks for getting to me on this, that's helpful. I'll work on a fix in
the next day or so...

**Comment by artemiuzzz** [comment]
I've pulled this fix but it didn't help me. But I found such workaround:
add this line:
`set(WEBRTC_LIBRARY_RELEASE ${WEBRTC_LIBRARIES_RELEASE})`
before this:
```
include(${CMAKE_ROOT}/Modules/SelectLibraryConfigurations.cmake)
select_library_configurations(WEBRTC)
```
I'm not sure that I correctly understand this cmake script, but it seems that `select_library_configurations ` looks for basename_LIBRAR**Y**_RELEASE(DEBUG), not basename_LIBRAR**IES**_RELEASE(DEBUG)
https://cmake.org/cmake/help/v3.7/module/SelectLibraryConfigurations.html

> If only basename_LIBRARY_RELEASE is defined, ...

**Comment by auscaster** [comment]
You will need to regenerate your cmake files before the fix will work, or
just remove build/CMakeCache.txt

Good point on select_library_configurations, I came to the same conclusion
also!

**Comment by artemiuzzz** [comment]
> You will need to regenerate your cmake files before the fix will work, or
> just remove build/CMakeCache.txt

Didn't help. Uncommented messages output show this:
> WEBRTC_LIBRARIES_DEBUG: /home/artem/webrtc-checkout/src/out/Debug/obj/third_party/boringssl/libboringssl.a;/home/artem/webrtc-checkout/src/out/Debug/obj/third_party/protobuf/libprotobuf_full.a;/home/artem/webrtc-checkout/src/out/Debug/obj/webrtc/libwebrtc.a;/home/artem/webrtc-checkout/src/out/Debug/obj/webrtc/system_wrappers/libfield_trial_default.a;/home/artem/webrtc-checkout/src/out/Debug/obj/webrtc/system_wrappers/libmetrics_default.a
> WEBRTC_LIBRARIES_RELEASE: /home/artem/webrtc-checkout/src/out/Release/obj/third_party/boringssl/libboringssl.a;/home/artem/webrtc-checkout/src/out/Release/obj/third_party/protobuf/libprotobuf_full.a;/home/artem/webrtc-checkout/src/out/Release/obj/webrtc/libwebrtc.a;/home/artem/webrtc-checkout/src/out/Release/obj/webrtc/system_wrappers/libfield_trial_default.a;/home/artem/webrtc-checkout/src/out/Release/obj/webrtc/system_wrappers/libmetrics_default.a
> WEBRTC_LIBRARIES: WEBRTC_LIBRARY-NOTFOUND;/home/artem/webrtc-checkout/src/out/Debug/obj/third_party/boringssl/libboringssl.a;/home/artem/webrtc-checkout/src/out/Debug/obj/third_party/protobuf/libprotobuf_full.a;/home/artem/webrtc-checkout/src/out/Debug/obj/webrtc/libwebrtc.a;/home/artem/webrtc-checkout/src/out/Debug/obj/webrtc/system_wrappers/libfield_trial_default.a;/home/artem/webrtc-checkout/src/out/Debug/obj/webrtc/system_wrappers/libmetrics_default.a;/home/artem/webrtc-checkout/src/out/Release/obj/third_party/boringssl/libboringssl.a;/home/artem/webrtc-checkout/src/out/Release/obj/third_party/protobuf/libprotobuf_full.a;/home/artem/webrtc-checkout/src/out/Release/obj/webrtc/libwebrtc.a;/home/artem/webrtc-checkout/src/out/Release/obj/webrtc/system_wrappers/libfield_trial_default.a;/home/artem/webrtc-checkout/src/out/Release/obj/webrtc/system_wrappers/libmetrics_default.a

But I still can use the workaround, so it's not a problem for now.

**Comment by auscaster** [comment]
If its not too much trouble would you be able to submit a PR with your fix?
If it works I will merge it in

**Comment by artemiuzzz** [comment]
Sure, here it is https://github.com/sourcey/libsourcey/pull/164
