### ISSUE TITLE
Replacing adapters leads to crash (when overriding `onSocketRecv`)

### ISSUE THREAD

**Issue by Malesio** [sourcey/libsourcey#161]
Hello Kam,

I've been testing some things with the HTTP module, and so I tried to implement some multi-request connection adapter thingy. The one-time use nature of the current implementation isn't really convenient, especially when dealing with a REST API. 
Although replacing the default `ConnectionAdapter` instance with a Websocket adapter works pretty well, this snippet leads to a segfault : 
```cpp
ClientConnection::Ptr connection = createConnection(u);
connection->replaceAdapter(new ConnectionAdapter(connection.get(), HTTP_RESPONSE));
connection->request().setURI("/");
connection->request().setHost(u.host(), u.port());
connection->send();
```
where `u` is here an instance of `URL`. I obviously call `waitForShutdown` so there isn't any destroyed pending operation.
I also noticed that this `replaceAdapter` call is the same as the one in the `ClientConnection` constructor.

**More details about the crash**

Debugger reported that this is caused by dereferencing a null pointer, occuring in `onSocketRecv` of some `SocketAdapter` instance. The `ptr` member of `ref` is showed as a null pointer, even though the `alive` field is true. That means the pointer is deleted somewhere, and the alive flag isn't toggled to `false`.

I'm tempted to think that something is broken in the `replaceAdapter` method, which sounds somewhat weird, mainly because the Websocket adapter is working just fine. I'll do some further investigation, though.

Note: when run with Valgrind, the crash somehow doesn't seem to happen.

**Comment by auscaster** [comment]
Hi Malesio

Interesting find there, I'm not sure this is directly related to `replaceAdapter` since it just replaces the pointer, and the ConnectionAdapter gets sent to the garbage collector, but I'm certainly interested to see what you turn up. Perhaps there some dangling callbacks somewhere?

**Comment by Malesio** [comment]
I think I'll just compare data flows with and without the problematic call to see if there's any differences between them, i.e. freed callbacks that get called by the new adapter. This null pointer really makes me think. 
Anyway, sleep time here (utc+2), I'll catch you later then.

**Comment by auscaster** [comment]
Spain? I'm currently on the costa del sol :)

**Comment by Malesio** [comment]
I can confirm that the problem is not related to `replaceAdapter`, because `onSocketConnect` gets called the same way and doesn't crash. I enabled trace logging on every construction/destruction of SocketAdapter, ConnectionAdapter, etc. and everything seems ok. 
Another thing I can say is that as stated above, the new ConnectionAdapter is properly set up and works during the connection phase, and then loses all of its receivers (the ClientConnection pointer, mainly) for whatever reason when the HTTP parser is dispatching the response body. 
Still on my way to solve this. 

Haha no, I live in the country a bit more to the north, and it's sadly a lot less sunny here. Lucky you :)

**Comment by auscaster** [comment]
I added a test for your case, but no errors:

```
    describe("replace connection adapter", []() {
        auto url = http::URL("https://sourcey.com/");
        auto conn = http::Client::instance().createConnection(url);
        conn->Headers += [&](http::Response& response) {
            // std::cout << "On response headers: " << response << endl;
        };
        conn->Payload += [&](const MutableBuffer& buffer) {
            // std::cout << "On payload: " << buffer.size() << ": " << buffer.str() << endl;
        };
        conn->Complete += [&](const http::Response& response) {
            // std::cout << "On response complete: " << response << endl;
            conn->close();
        };

        conn->replaceAdapter(new http::ConnectionAdapter(conn.get(), HTTP_RESPONSE));
        conn->request().setURI("/");
        conn->request().setHost(url.host(), url.port());
        conn->send();

        uv::runLoop();

        expect(conn->closed());
        expect(!conn->error().any());
    });
```

Let me know if you can expand on the issue or provide a breaking test. Perhaps you are destroying the connection instance differently and it goes out of scope?

**Comment by Malesio** [comment]
The test you provided runs perfectly fine, however I still get these segfaults.
Source code I run : 
```cpp
#include <iostream>
#include <scy/http/client.h>
#include <scy/net/sslmanager.h>

using namespace scy;

int main(int argc, char *argv[])
{
    Logger::instance().add(new ConsoleChannel("debug", Level::Trace));
    net::SSLManager::initNoVerifyClient();

    auto url = http::URL("https://www.google.com/");
    auto conn = http::Client::instance().createConnection(url);
    conn->Headers += [&](http::Response& response) {
        std::cout << "On response headers: " << response << std::endl;
    };
    conn->Payload += [&](const MutableBuffer& buffer) {
        std::cout << "On payload: " << buffer.size() << ": " << buffer.str() << std::endl;
    };
    conn->Complete += [&](const http::Response& response) {
        std::cout << "On response complete: " << response << std::endl;
        conn->close();
    };

    conn->replaceAdapter(new http::ConnectionAdapter(conn.get(), HTTP_RESPONSE));
    conn->request().setURI("/");
    conn->request().setHost(url.host(), url.port());
    conn->send();

    uv::runLoop();
    Logger::destroy();

    return 0;
}
```

Compilation : `g++ -std=c++14 -g -o replace_adapter_test replace_adapter_test.cpp -lscy_http -lscy_net -lscy_base -llibuv` (latest version of LibSourcey, built as shared libraries, g++ 5.4.1).

The code is exactly the same (although the SSL initialisation is needed because of HTTPS) as what you posted above, and that one still does segfault in `onSocketRecv`. The HTTP test program works, this one doesn't.

Besides, the connection has no way getting out of scope like that. The instance of Connection is always held by the Client in this case. This is definitely a weird bug. Could you try to run this source code so I could know if my building environment is definitely messed up ?

**Comment by auscaster** [comment]
I tested and all works for me - no segfaults.

My gcc is `6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12)`

Compiled LibSourcey:

```
cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=ON \
         -DBUILD_APPLICATIONS=ON -DBUILD_MODULES=OFF \
         -DBUILD_SAMPLES=ON -DBUILD_TESTS=ON \
         -DBUILD_MODULE_base=ON -DBUILD_MODULE_crypto=ON \
         -DBUILD_MODULE_json=ON -DBUILD_MODULE_net=ON \
         -DBUILD_MODULE_util=ON -DBUILD_MODULE_http=ON
sudo make install
```

Build the app:

```
g++ -std=c++14 -g -o replace_adapter_test replace_adapter_test.cpp `pkg-config --libs --cflags libsourcey`
```

Note: I had to makie an adjustment to libsourcey.pc, so please sync with master if you want to use the above coimmand with pkg-config.

Output
```
On response headers: HTTP/1.1 302 Found
Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
Cache-Control: private
Content-Length: 257
Content-Type: text/html; charset=UTF-8
Date: Tue, 04 Jul 2017 11:10:40 GMT
Location: https://www.google.es/?gfe_rd=cr&ei=sHdbWcz4LbHBXqungqgK
Referrer-Policy: no-referrer


On payload: 257: <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.es/?gfe_rd=cr&amp;ei=sHdbWcz4LbHBXqungqgK">here</A>.
</BODY></HTML>

On response complete: HTTP/1.1 302 Found
Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
Cache-Control: private
Content-Length: 257
Content-Type: text/html; charset=UTF-8
Date: Tue, 04 Jul 2017 11:10:40 GMT
Location: https://www.google.es/?gfe_rd=cr&ei=sHdbWcz4LbHBXqungqgK
Referrer-Policy: no-referrer

```

**Comment by Malesio** [comment]
Alright this is very likely a me problem. I just tested the app on an old Debian Jessie VM with gcc 4.9.2, updated to the latest version of LibSourcey, compiled the exact same way as you, same command line with `pkg-config`, and it just worked like a charm. I guess I need to reinstall some things, and I'll tell you if that issue could be closed then.

**Comment by Malesio** [comment]
Problem solved. It appears that I was linking wrong dynamic libraries. That explains why the test case you provided did work and not mine. Although, it is confusing that the required internal dependencies (libuv, http_parser, zlib, minizip) install into a non-standard location (aka `/usr/local/share/libsourcey/vendor/lib`). Adding it to the LD_LIBRARY_PATH does the trick, though. 
You certainly have good reasons to embed some of the dependencies directly into LibSourcey, for the sake of simplicity, but well, since all those dependencies are available from the system's package manager (e.g. on Ubuntu, `libhttp-parser-dev`, `libminizip-dev`, `zlib1g-dev` and `libuv1-dev` are all available, and IIRC, they're also available on Red Hat, Arch, etc.), this isn't really a problem.
In my case, I was facing inconsistencies between the package manager's version of `http_parser` and the one provided in LibSourcey.

Feel free to close this, sorry to have bothered you with this. I'll come back soon with new issues about the `av` module ;)

**Comment by auscaster** [comment]
Yes that makes sense. Glad you got it sorted!!
