### ISSUE TITLE
Installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by GhostGumm** [sourcey/libsourcey#165]
Hi,
I'am trying to install the LibSourcey with Webrtc and FFmpeg support. 

When i CMake like this (from /tmp/libsourcey/build) : 
`cmake .. -DWITH_WEBRTC=ON -DWITH_FFMPEG=ON `

I allways get the same errors.

FFMPEG ones :
`
CMake Warning at cmake/FindFFmpeg.cmake:152 (message):
  Required component SWSCALE missing.
`

And a WebRTC one : 
`CMake Error at cmake/LibSourceyIncludes.cmake:72 (message):
  Failed to include dependency: WebRTC.  Please build and install
  dependencies before using CMake.
Call Stack (most recent call first):
  LibSourcey.cmake:243 (find_dependency)
  CMakeLists.txt:35 (include)
`
I'am rolling on Ubuntu 16.04 LTS

I did everything, compiling Webrtc manually, using webrtcbuilds. Same for FFmpeg i went through the whole process, changed the Find***.cmake paths, but yet nothing worked, i can only compile witho no option and  only SSL support. 

Any help would be much appreciated.

**Comment by auscaster** [comment]
Hey there

The FFmpeg issue shouldn't be a problem, but it looks like the scripts can't resolve the WebRTC libraries. Can you please send your full build command and the WebRTC path including the path to the compiled WebRTC library `libwebrtc_full.a`?

**Comment by GhostGumm** [comment]
Thank you for the fast answer .
Here is my configuration :
-----------------------------------------------
Build Command : 
in ~/tmp/libsourcey/build
 cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DWITH_WEBRTC=ON
------------------------------------------------
Full WebRTC Path : 
~/tmp/webrtcbuilds
-------------------------------------------------
Path to libwebrtc_full.a
~/tmp/webrtc_precompiled/lib/x64/Release
 
i got : 
~/tmp/depot_tools
~/tmp/webrtcbuilds
~/tmp/libsourcey
~/tmp/webrtc_precompiled

**Comment by GhostGumm** [comment]
After 6 days I just managed to compile !!
The problem was that the regexp declaration in the cmake file : FindWebrtc was too complicated i guess. 
I just added libwebrtc_full at the start of the declaration, and it compiled easy. 

I'am trying to compile the FFMPEG part now.

**Comment by happyj2me** [comment]
Hi, @GhostGumm ,I can't compile webrtc, Would you pls send me the file FindWebrtc.cmake after you modified,  my email : happyj2me@aliyun.com  , Thanks !

**Comment by auscaster** [comment]
Hey guys, you need to specify the WebRTC path for cmake, ie:
```
cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DWITH_WEBRTC=ON -DWEBRTC_ROOT_DIR=/path/to/webrtc
```

Check out these files for references:

https://github.com/sourcey/libsourcey/blob/master/circle.yml
https://github.com/sourcey/libsourcey/blob/master/BUILD.md
