### ISSUE TITLE
webrtcstreamerd often fails to loop the video

### ISSUE THREAD

**Issue by michaelfig** [sourcey/libsourcey#166]
Hi,

When streaming the video, it often hangs when it reaches the end of file, instead of looping as expected.  Here is part of the trace, note that `Decoder EOF: -541478725`, so the av/src/mediacapture.cpp bails instead of looping.

Any thoughts?

Thanks,
Michael.

```
22:35:57 [trace] [audiopacketmodule.cpp(87)] Audio frame captured
22:35:57 [trace] [mediacapture.cpp(232)] Decoded Audio: time=60046802, pts=1324032
22:35:57 [trace] [mediacapture.cpp(189)] Read frame: pts=1325056, dts=1325056
22:35:57 [trace] [mediacapture.cpp(154)] Emit: 8192
22:35:57 [trace] [packetstream.cpp(281)] Processing packet: Active: PlanarAudioPacket
22:35:57 [trace] [packetstream.cpp(336)] Proxying packet: Active: PlanarAudioPacket
22:35:57 [trace] [packetstream.cpp(360)] Emit: 8192
22:35:57 [trace] [audiopacketmodule.cpp(87)] Audio frame captured
22:35:57 [trace] [mediacapture.cpp(232)] Decoded Audio: time=60093242, pts=1325056
22:35:57 [trace] [mediacapture.cpp(189)] Read frame: pts=1324032, dts=1324032
22:35:57 [trace] [mediacapture.cpp(250)] Decoder EOF: -541478725
22:35:57 [debug] [audiopacketmodule.cpp(189)] Send audio1
22:35:57 [trace] [audiobuffer.cpp(105)] Read samples: 440
22:35:57 [trace] [audiopacketmodule.cpp(204)] Send audio
(bitrate_allocator.cc:83): Current BWE 5256486
22:35:57 [debug] [audiopacketmodule.cpp(189)] Send audio1
22:35:57 [trace] [audiobuffer.cpp(105)] Read samples: 440
22:35:57 [trace] [audiopacketmodule.cpp(204)] Send audio
22:35:57 [debug] [audiopacketmodule.cpp(189)] Send audio1
22:35:57 [trace] [audiobuffer.cpp(105)] Read samples: 440
22:35:57 [trace] [audiopacketmodule.cpp(204)] Send audio
22:35:57 [debug] [audiopacketmodule.cpp(189)] Send audio1
22:35:57 [trace] [audiobuffer.cpp(105)] Read samples: 440
22:35:57 [trace] [audiopacketmodule.cpp(204)] Send audio
```

**Comment by michaelfig** [comment]
FWIW, I appear to get more errors when streaming to Firefox 54 rather than Chrome.

**Comment by auscaster** [comment]
Hi Michael

I have never experienced this issue with the provided test video. Are you
having the issues with this video or another one? The seek function works
directly with ffmpeg APIs, so hopefully it's not a lower level issue.

Perhaps you could try testing with a standalone mediacapture instance, and
also with raw ffmpeg API just to be sure where the issue lies.

I will be away for a couple of weeks so won't be able to test this, but let
me know how you get on.

**Comment by michaelfig** [comment]
I'm using the provided video.  Sometimes I get an EOF error, but the mediacapturer thread still loops (setRepeating is true).  When it fails to loop, the capturer doesn't report any errors, as if the thread was cancelled, but I don't get any "Stopping" messages from the capturer.

**Comment by auscaster** [comment]
Please try to create a minimal failing test case and I may be able to help
you while away. The mediacapturer should exit on EOF.

**Comment by michaelfig** [comment]
This turned (no pun intended) out to be a problem with my coturn server.

When UDP from the client was blocked to the webrtcstreamerd, but not to the STUN service running in the same coturn process as my TURNS service, after a bit, the turnserver would give a `closed (2nd stage)`...`reason: allocation watchdog determined stale session state` and wedge the TURNS connection while cleaning up the STUN session for that client.

I'm working with the coturn folks to figure out a solution.
