### ISSUE TITLE
Mac OSX 10.11 linking error

### ISSUE THREAD

**Issue by Qulyf** [sourcey/libsourcey#169]
Hello,
I could almost build the lib successfully except the webrtc linking error. The build.sh works well, runs with -x -e -l jsoncpp.  But I have to manully do the lib(debug and release) copy. No libwebrtc_full.a generate. I've seen these 'Undefined symbols for architecture x86_64' errors before but don't know why, different clang version? The symbols are just in the *.o file, why undefined? Does anyone come up with this webrtc problem before? I really need some hints and thank you for any help.   Errors are 

**[100%] Linking CXX executable webrtcstreamerd
clang: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/usr/local/share/libsourcey/vendor/lib'
ld: warning: directory not found for option '-L/Users/Qulyf/Github/libsourcey/build/src/base'
ld: warning: directory not found for option '-L/Users/Qulyf/Github/libsourcey/build/src/av'
ld: warning: directory not found for option '-L/Users/Qulyf/Github/libsourcey/build/src/crypto'
ld: warning: directory not found for option '-L/Users/Qulyf/Github/libsourcey/build/src/util'
Undefined symbols for architecture x86_64:
  "_AudioConvertHostTimeToNanos", referenced from:
      webrtc::AudioDeviceMac::implDeviceIOProc(AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*) in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::implInDeviceIOProc(AudioBufferList const*, AudioTimeStamp const*) in libwebrtc.a(audio_device_mac.o)
  "_AudioConverterDispose", referenced from:
      webrtc::AudioDeviceMac::StopRecording() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::StopPlayout() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::HandleStreamFormatChange(unsigned int, AudioObjectPropertyAddress) in libwebrtc.a(audio_device_mac.o)
  "_AudioConverterFillComplexBuffer", referenced from:
      webrtc::AudioDeviceMac::implDeviceIOProc(AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*) in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::CaptureWorkerThread() in libwebrtc.a(audio_device_mac.o)
  "_AudioConverterNew", referenced from:
      webrtc::AudioDeviceMac::SetDesiredPlayoutFormat() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::InitRecording() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::HandleStreamFormatChange(unsigned int, AudioObjectPropertyAddress) in libwebrtc.a(audio_device_mac.o)
  "_AudioDeviceCreateIOProcID", referenced from:
      webrtc::AudioDeviceMac::InitPlayout() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::InitRecording() in libwebrtc.a(audio_device_mac.o)
  "_AudioDeviceDestroyIOProcID", referenced from:
      webrtc::AudioDeviceMac::StopRecording() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::StopPlayout() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::implDeviceIOProc(AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*) in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::implInDeviceIOProc(AudioBufferList const*, AudioTimeStamp const*) in libwebrtc.a(audio_device_mac.o)
  "_AudioDeviceStart", referenced from:
      webrtc::AudioDeviceMac::StartRecording() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::StartPlayout() in libwebrtc.a(audio_device_mac.o)
  "_AudioDeviceStop", referenced from:
      webrtc::AudioDeviceMac::StopRecording() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::StopPlayout() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::implDeviceIOProc(AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*) in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::implInDeviceIOProc(AudioBufferList const*, AudioTimeStamp const*) in libwebrtc.a(audio_device_mac.o)
  "_AudioGetCurrentHostTime", referenced from:
      webrtc::AudioDeviceMac::implDeviceIOProc(AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*) in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::implInDeviceIOProc(AudioBufferList const*, AudioTimeStamp const*) in libwebrtc.a(audio_device_mac.o)
  "_AudioHardwareUnload", referenced from:
      webrtc::AudioDeviceMac::Terminate() in libwebrtc.a(audio_device_mac.o)
  "_AudioObjectAddPropertyListener", referenced from:
      webrtc::AudioDeviceMac::Init() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::InitPlayout() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::InitRecording() in libwebrtc.a(audio_device_mac.o)
  "_AudioObjectGetPropertyData", referenced from:
      webrtc::AudioDeviceMac::InitDevice(unsigned short, unsigned int&, bool) in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::GetNumberDevices(unsigned int, unsigned int*, unsigned int) in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::GetDeviceName(unsigned int, unsigned short, char*) in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::InitPlayout() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::SetDesiredPlayoutFormat() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::InitRecording() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::HandleDeviceChange() in libwebrtc.a(audio_device_mac.o)
      ...
  "_AudioObjectGetPropertyDataSize", referenced from:
      webrtc::AudioDeviceMac::GetNumberDevices(unsigned int, unsigned int*, unsigned int) in libwebrtc.a(audio_device_mac.o)
  "_AudioObjectHasProperty", referenced from:
      webrtc::AudioDeviceMac::InitPlayout() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::StopPlayout() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioMixerManagerMac::SpeakerVolume(unsigned int&) const in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::SpeakerMute(bool&) const in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::MicrophoneMute(bool&) const in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::MicrophoneVolume(unsigned int&) const in libwebrtc.a(audio_mixer_manager_mac.o)
  "_AudioObjectIsPropertySettable", referenced from:
      webrtc::AudioMixerManagerMac::SetSpeakerVolume(unsigned int) in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::SpeakerVolumeIsAvailable(bool&) in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::SpeakerMuteIsAvailable(bool&) in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::SetSpeakerMute(bool) in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::MicrophoneMuteIsAvailable(bool&) in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::SetMicrophoneMute(bool) in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::MicrophoneVolumeIsAvailable(bool&) in libwebrtc.a(audio_mixer_manager_mac.o)
      ...
  "_AudioObjectRemovePropertyListener", referenced from:
      webrtc::AudioDeviceMac::Terminate() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::StopRecording() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::StopPlayout() in libwebrtc.a(audio_device_mac.o)
  "_AudioObjectSetPropertyData", referenced from:
      webrtc::AudioDeviceMac::Init() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::SetDesiredPlayoutFormat() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioDeviceMac::InitRecording() in libwebrtc.a(audio_device_mac.o)
      webrtc::AudioMixerManagerMac::SetSpeakerVolume(unsigned int) in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::SetSpeakerMute(bool) in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::SetMicrophoneMute(bool) in libwebrtc.a(audio_mixer_manager_mac.o)
      webrtc::AudioMixerManagerMac::SetMicrophoneVolume(unsigned int) in libwebrtc.a(audio_mixer_manager_mac.o)
      ...
  "_CGEventSourceKeyState", referenced from:
      webrtc::AudioDeviceMac::KeyPressed() in libwebrtc.a(audio_device_mac.o)
  "typeinfo for rtc::MessageHandler", referenced from:
      typeinfo for scy::wrtc::AudioPacketModule in libscy_webrtc.a(audiopacketmodule.cpp.o)
  "typeinfo for cricket::VideoCapturer", referenced from:
      typeinfo for scy::wrtc::VideoPacketSource in libscy_webrtc.a(videopacketsource.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [webrtc/samples/webrtcstreamer/webrtcstreamerd] Error 1
make[1]: *** [webrtc/samples/webrtcstreamer/CMakeFiles/webrtcstreamer.dir/all] Error 2
make: *** [all] Error 2**

**Comment by auscaster** [comment]
It seems like an issue faced by many mac users.

By the way you should use the same command as ubuntu: `./build.sh -c x64 -b branch-heads/59`

I can be a clang version mismatch. Some helpful resources:
https://groups.google.com/d/msg/discuss-webrtc/PniiO9BumHA/JZGo0LdTHAAJ
https://github.com/pristineio/webrtc-build-scripts/issues/166
https://groups.google.com/forum/#!topic/discuss-webrtc/axFMP4rRQb8

**Comment by auscaster** [comment]
You can also try compiling WebRTC directly from source and you might find out where the issue lies: https://webrtc.org/native-code/development/

**Comment by auscaster** [comment]
Did you make any progress with this?

**Comment by Qulyf** [comment]
I'm focus on developing on Ubuntu right now, and the answer is still no. I've looked through the build script of the source, it's a little complex, just need more time...

**Comment by happyj2me** [comment]
@Qulyf  any progress ?  I faced the same problem as you now

**Comment by auscaster** [comment]
There seems to be a lot of similar WebRTC related issues when googling, have you checked all references for a solution?

https://www.google.es/search?q=%22Undefined+symbols+for+architecture+x86_64%22+webrtc&oq=%22Undefined+symbols+for+architecture+x86_64%22+webrtc&aqs=chrome..69i57.3023j0j7&sourceid=chrome&ie=UTF-8

**Comment by happyj2me** [comment]
I don't know whether cmake find framework AVFoundation correctly , how to see cmake's verbose output  when compile

if(APPLE)
  message(STATUS "Including APPLE's foundation and AVFoundation frameworks")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -framework Foundation -framework AVFoundation")
  #set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /SAFESEH:NO")
  #set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} /SAFESEH:NO")
endif()
