### ISSUE TITLE
Help! About WebRTC issues using libsourcey

### ISSUE THREAD

**Issue by happyj2me** [sourcey/libsourcey#173]
Hi @auscaster , I work on mac and try to create a project for libsourcey use CLion(A c++ IDE on mac), I do the following jobs already but Webrtc still not compiled by CLion:

 1. checkout webrtc-builds and build webrtc on mac success using command 
     ./build.sh -l jsoncpp -e
     /Users/zhoull/refcode/webrtc-builds/out/webrtc-19266-fe6d9ff-mac-x64/lib/x64
jinghang-macbook:x64 zhoull$ tree -L 2
├── Debug
│   ├── libboringssl.a
│   ├── libfield_trial_default.a
│   ├── libmetrics_default.a
│   ├── libprotobuf_full.a
│   ├── libprotobuf_lite.a
│   ├── libprotoc_lib.a
│   ├── libsystem_wrappers.a
│   └── libwebrtc.a
└── Release
    ├── libboringssl.a
    ├── libfield_trial_default.a
    ├── libmetrics_default.a
    ├── libprotobuf_full.a
    ├── libprotobuf_lite.a
    ├── libprotoc_lib.a
    ├── libsystem_wrappers.a
    └── libwebrtc.a

  2.  turn on option WITH_WEBRTC in file libSourcey.cmake
        set_option(WITH_WEBRTC          "Include WebRTC support"               ON)

 3.  set WEBRTC_ROOT_DIR in file FindWebRTC.cmake
     set(WEBRTC_ROOT_DIR "/Users/zhoull/refcode/webrtc-builds/out/webrtc-19266-fe6d9ff-mac-x64" CACHE STRING "Where is the WebRTC root directory located?")

 4. brew install ffmpeg  and ffmpeg-3.1.1 already installed

  Outputs from CLion : 
/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /Users/zhoull/refcode/libsourcey
-- Including APPLE's foundation and AVFoundation frameworks
-- Checking for one of the modules 'opencv'
-- - Linking dependency libuv with libraries: 
-- - Linking dependency minizip with libraries: 
-- - Linking dependency http_parser with libraries: 
-- Including module archo
-- Including dependency: FFmpeg
-- Module not defined FFmpeg 
-- Including module av
-- Including module base
-- Including dependency: SSL
-- Including dependency: OpenSSL
-- Including OpenSSL TRUE
-- Including module crypto
-- Including dependency: SSL
-- Including dependency: OpenSSL
-- Including OpenSSL TRUE
-- Including module http
-- Including module json
-- Including dependency: SSL
-- Including dependency: OpenSSL
-- Including OpenSSL TRUE
-- Including module net
-- Including module sched
-- Including dependency: SSL
-- Including dependency: OpenSSL
-- Including OpenSSL TRUE
-- Including module socketio
-- Including dependency: SSL
-- Including dependency: OpenSSL
-- Including OpenSSL TRUE
-- Including module stun
-- Including dependency: SSL
-- Including dependency: OpenSSL
-- Including OpenSSL TRUE
-- Including module symple
-- Including module turn
-- Including module util
-- Creating 'libsourcey.pc'
-- Creating 'libsourcey.h'
-- 
--   Platform:
--     Host:                        Darwin 16.5.0 x86_64
--     CMake:                       3.8.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               Debug
-- 
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--     C++ flags (Release):         -std=c++1y  -Wall -Wno-long-long -pthread -fno-omit-frame-pointer -O3 -DNDEBUG   -DNDEBUG
--     C++ flags (Debug):           -std=c++1y  -Wall -Wno-long-long -pthread -fno-omit-frame-pointer -g  -O0 -DDEBUG -D_DEBUG -ggdb3
--     C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
--     C flags (Release):           -Wall -Wno-long-long -pthread -fno-omit-frame-pointer -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -Wall -Wno-long-long -pthread -fno-omit-frame-pointer -g  -O0 -DDEBUG -D_DEBUG -ggdb3
--     Linker flags (Release):
--     Linker flags (Debug):
-- 
--   Build Components:
-- 
--      Dependencies:               libuv;zlib;minizip;http_parser
--      Modules:                    archo;av;base;crypto;http;json;net;sched;socketio;stun;symple;turn;util;webrtc
--      Applications:               
--      Samples:                    
--      Tests:                      
-- 
--   Other third-party libraries:
-- 
--     Use OpenSSL:                 YES
--     Use FFmpeg:                  NO
--     Use OpenCV:                  NO
--     Use WebRTC:                  NO
--     Use Poco:                    NO
--     Use wxWidgets:               NO
-- 
--     Install path:                /usr/local
-- 
--     libsourcey.h is in:          /usr/local/include/libsourcey.h
-- -----------------------------------------------------------------
-- 
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   archo
   av
   base
   crypto
   http
   http_parser
   json
   libuv
   minizip
   net
   sched
   socketio
   stun
   symple
   turn
   util
   zlib

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/zhoull/refcode/libsourcey/cmake-build-debug

[Finished]

**Comment by happyj2me** [comment]
I know the reason why webrtc is not build by CLion ,  config items cached in CMakeCache.txt not changed after I modified the libsourcey.cmake

**Comment by auscaster** [comment]
Hi there, unfortunately I don't use CLion so can't comment of support. There are a number of users who are using libsourcey on Xcode and iOS - maybe you could try compiling using Xcode first?

**Comment by happyj2me** [comment]
@auscaster , it works for me now when use CLion to compile on mac , thanks very much for your reply!  I use webrtc to develop some P2P video chat apps mainly for  Android Phones,  So I use Android Studio for my daily programing , One big problem i meet is I don't know how to debug webrtc native code use Android Studio,  Android Studio seems not support ninja to comiple webrtc

**Comment by auscaster** [comment]
Great, glad you got it sorted! Good luck with your project
