### ISSUE TITLE
Fail to cmake with WEBRTC=on

### ISSUE THREAD

**Issue by netmindms** [sourcey/libsourcey#174]
Hi!,
I am considering to use libsourcey for developing WebRTC native app.
I am trying to build libsourcey with prebuilt webrtc library in sourcey/webrtc-precompiled-builds repository for linux.
But I don't know how to set webrtc library path. When I run cmake with WITH_WEBRTC=ON, I encountered " Could NOT find WEBRTC (missing:  WEBRTC_LIBRARIES WEBRTC_INCLUDE_DIR)" error message.
I am using Ubuntu 16.04.

Please, Help me...

**Comment by happyj2me** [comment]
You need to modify file FoundWebRTC.cmake set set(WEBRTC_ROOT_DIR "/Users/zhoull/refcode/webrtc-builds/out/webrtc-19266-fe6d9ff-mac-x64" CACHE STRING "Where is the WebRTC root directory located?")

/Users/zhoull/refcode/webrtc-builds/out/webrtc-19266-fe6d9ff-mac-x64  is  my webrtc'build base dir ,  it contains webrtc's include files and libs

you can refer https://github.com/sourcey/webrtc-builds to build webrtc

**Comment by auscaster** [comment]
No, you don't need to modify any files :)

You need to specify the WebRTC path for cmake, ie:

```
cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DWITH_WEBRTC=ON -DWEBRTC_ROOT_DIR=/path/to/webrtc
```

Check out these files for references:

https://github.com/sourcey/libsourcey/blob/master/circle.yml
https://github.com/sourcey/libsourcey/blob/master/BUILD.md

**Comment by happyj2me** [comment]
@auscaster  It's my first time to use cmake , so i modified you files and it works also ,but i think your solution is better !

**Comment by auscaster** [comment]
OK cool. If its working please close this issue. Good luck with your
project!

**Comment by netmindms** [comment]
I downloaded the prebuilt library( tar file ) and extracted to ~/prj/prebuiltwebrtc/.
The extracted folder has as follwing sub folders.

prebuiltwebrtc
├── include
│   ├── third_party
│   └── webrtc
└── lib
    └── x64

and x64 folder has two folers that has each target library.(Debug and Release)
In this case, what can I set as WEBRTC_ROOT_DIR ?

**Comment by auscaster** [comment]
/full/absolute/path/to/prj/prebuiltwebrtc/

**Comment by netmindms** [comment]
Ok. The build is successull. 
Thanks.
