### ISSUE TITLE
Media Server sample missing javascript files?

### ISSUE THREAD

**Issue by cwigginscti** [sourcey/libsourcey#175]
I've built libsourcey on Windows 10 and am going thru some samples. HTTP echo works fine, but on the MediaServer client side, index.html references 3 symple.player javascript files. I found symple.player.js in the webrtcstreamer sample, but I can't find symple.player.flash.js or symple.player.mjpeg.js. Is this sample still functional?

Great design approach, BTW - just getting my head around all the pieces.

**Comment by auscaster** [comment]
Hi there, and sorry for the confusing sample! The sample client code is currently in disarray since there has been so many updates to the symple player since it was built, and I haven't had a chance to fix it yet.

Right now it is better as a use case or example code for how you can stream video over a socket/connection (raw, http, turn, websocket) on the server side.

**Comment by cwigginscti** [comment]
OK, thanks. Are there any working samples you would suggest? We are probably going to use WebRTC but would need to stream to browser clients. I was hoping to try things out without the WebRTC build first just to make sure I understood the dependencies.

**Comment by cwigginscti** [comment]
Also, looking at the WebRTCStreamer sample in libsourcey/src/webrtc/samples/webrtcstreamer/, the client directory says it's for "Symple WebRTC Video Chat Demo" . Is that correct? I haven't tried running it, but the client directory Readme is the same for both webrtccapturer and webrtcstreamer.

**Comment by auscaster** [comment]
OK great! webrtccapturer and webrtcstreamer are both working 100%. There
may be some code duplication between the clients since both are quite
similar.

**Comment by cwigginscti** [comment]
Trying to build libsourcey on Windows with the prebuild WebRTC libraries - the windows archives (looked at 58 and 59) don't have the include directory but the Linux versions do. Do I get the includes from some other location?

**Comment by auscaster** [comment]
Yes that would be fine! The headers are the same for all platforms
