### ISSUE TITLE
error: field ‘_ctx’ has incomplete type ‘EVP_MD_CTX {aka evp_md_ctx_st}’ with OpenSSL 1.1.x

### ISSUE THREAD

**Issue by ibroheem** [sourcey/libsourcey#179]
Got the above error when building with OpenSSL v1.1.x.
The lib compiled fine with 1.0.x (actually 1.0.2)
I believe it should be explicitly stated that the library should use the OpenSSL 1.0.2 versions.

Thanks

**Comment by auscaster** [comment]
Thanks for the bug report, you are quite right.

Some macros need to be added to support the latest version of OpenSSL.

I am away for a couple of weeks so would accept a PR, otherwise please use 1.0.x for now.

**Comment by ibroheem** [comment]
**I already used the 1.0.2**

Now I get the error @ runtime:
> Cannot create SSL_CTX object: error:140A90A1

Unless I link against -lssl and use the SSL_library_init();
