### ISSUE TITLE
FindOpenCV.cmake semi-broken

### ISSUE THREAD

**Issue by dshadowwolf** [sourcey/libsourcey#18]
The code has a few bugs, one in the handling of a passed-in 'OpenCV_INCLUDE_DIR' - which is required to include the 'opencv2' part of the path and the version detection, another with part of the auto-detection of the include path being commented out and a third with the detection of the libraries, where it doesn't attempt to look in the correct places for libraries on a distribution setup to be (primarily) 64bit but with some 32bit libraries installed for legacy and/or applications which are not provided as 64bit.

I have a patch which fixes 2 of the 3 issues noted that I can provide if necessary. The first issue is one that I'm not certain how to properly fix, as I don't use CMake enough to be fully familiar and comfortable with the language, but the other two have been fixed.

**Comment by auscaster** [comment]
@dshadowwolf please add the updated file in a pull request and I will review your changes.

**Comment by dshadowwolf** [comment]
Sorry about that - I don't have this forked on github, so... here is a patch from git diff.

diff --git a/cmake/FindOpenCV.cmake b/cmake/FindOpenCV.cmake
index acb6a7a..76ad88f 100644
--- a/cmake/FindOpenCV.cmake
+++ b/cmake/FindOpenCV.cmake
diff --git a/cmake/FindOpenCV.cmake b/cmake/FindOpenCV.cmake
index acb6a7a..76ad88f 100644
--- a/cmake/FindOpenCV.cmake
+++ b/cmake/FindOpenCV.cmake
@@ -34,12 +34,11 @@ if (NOT OpenCV_INCLUDE_DIR)
       opencv2/core/core.hpp
     DOC 
       "OpenCV Include Directory"
-    #PATHS
-    #  /usr/local/include
-    #  /usr/include
+    PATHS
+       /usr/local/include
+       /usr/include
     )  
 endif()
-
 # ----------------------------------------------------------------------
 # Determine OpenCV version
 # ----------------------------------------------------------------------
@@ -105,6 +104,8 @@ if (NOT OpenCV_FOUND)
     PATHS
       /usr/lib 
       /usr/local/lib
+      /usr/lib64

**Comment by auscaster** [comment]
Thanks, closing this down now.
