### ISSUE TITLE
Which version of chrome webrtc does it support?

### ISSUE THREAD

**Issue by legokichi** [sourcey/libsourcey#184]
It is impossible to build with the latest libwebrtc by [this commitment](https://webrtc.googlesource.com/src/+/c8fa692ec44fd6ba4fa3d085ac3161a262fc18c5).

**Comment by auscaster** [comment]
Branch heads up to `60` (that I've tested) are supported. There are also precompiled libraries here: https://sourcey.com/precompiled-webrtc-libraries/
