### ISSUE TITLE
webrtcrecorder and webrtccapturer samples

### ISSUE THREAD

**Issue by logikaljay** [sourcey/libsourcey#185]
Heya,

Just wondering if these two samples are disabled for any particular reason.

I see they were disabled in a commit that closed #156.

Is that still an issue? Or can these two samples be re-enabled?

**Comment by auscaster** [comment]
Hi Jay,

Yes, they can be re-enabled!

**Comment by logikaljay** [comment]
Heya @auscaster,

Wondering if you could help me out - maybe point me in the right direction.

My Goal: create nodejs bindings for an application similar to webrtcrecorder.

I am attempting to get this built with `g++` so it will be easier to translate to a `bindings.gyp` file that node-gyp can build.

I have very basic things working - IE: creating an instance of a Logger, and logging some messages.

However when it comes to actually build the webrtcrecorder sample using `g++` I am all kinds of lost trying to figure out linking dependencies.

My build script so far:

```bash
c++ -o main \
	main.cpp signaler.cpp \
	-std=c++1y -fPIC  -Wall -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -O3 -DNDEBUG   -DNDEBUG \
	-D_GLIBCXX_USE_CXX11_ABI=0 \
	-I/webrtc-lib/include \
	-I/usr/local/include -I/usr/local/share/libsourcey/vendor/include \
	-I/usr/include \
	-DWEBRTC_POSIX -L/webrtc-lib/lib/x64/Release -lwebrtc_full \
	-I/usr/local/include -I/usr/local/share/libsourcey/vendor/include -L/usr/local/lib -lscy_sched -lscy_crypto -lscy_av -lscy_stun -lscy_webrtc -lscy_turn -lscy_http -lscy_json -lscy_util -lscy_archo -lscy_symple -lscy_socketio -lscy_net -lscy_base -lcrypto \
	-L/usr/local/share/libsourcey/vendor/lib  -llibuv -lzlib -lminizip -lhttp_parser -lssl \
	-I./ 
```

Output: https://gist.github.com/logikaljay/e4e86aa955063e8981762e2e65fbef71#file-linkingfailures-txt

I seem to be getting stuck on a lot of errors relating to `scy::crypto`

Installed libraries: https://gist.github.com/logikaljay/e4e86aa955063e8981762e2e65fbef71#file-installed-libraries

Any help or direction would be greatly appreciated.

**Comment by logikaljay** [comment]
Feel free to ignore the above, I got it working.

I think the problem was that I was adding all the libraries that `pkg-config` told me to for `webrtc_full`, after scraping my buildscript and starting again it works :)

for anyone who may stumble upon this, to build webrtcrecorder using `g++` you can do the following:

```bash
g++ -o main \
	main.cpp signaler.cpp \
	-fPIC \
	-DWEBRTC_POSIX \
	-std=c++1y \
	-D_GLIBCXX_USE_CXX11_ABI=0 \
	-I/usr/local/share/libsourcey/vendor/include \
	-I/webrtc-lib/include \
	-L/usr/local/share/libsourcey/vendor/lib \
	-lpthread -pthread \
	-lscy_webrtc -lscy_av -lscy_socketio -lscy_net -lscy_symple -lscy_http -lscy_crypto -lscy_base -lscy_util \
	-L/usr/lib/x86_64-linux-gnu -lavdevice -lavformat -lavcodec -lavutil -lavdevice -lavfilter -lswresample-ffmpeg -lswscale-ffmpeg \
	-llibuv \
	-L/webrtc-lib/lib/x64/Release -lwebrtc_full \
	-ldl -lX11 \
	-L/usr/local/share/libsourcey/vendor/lib/ -lhttp_parser \
	-I./
```
