### ISSUE TITLE
WebRTC build tools genereate empty output dir

### ISSUE THREAD

**Issue by sasmaster** [sourcey/libsourcey#187]
Hi,sorry for putting it here. But your repo with WebRTC generation script doesn't have issues feature.
Anyway,I tried that tool and the out/webrtc-20246-4af7366-win-x64 contains only empty 'include' and 'lib' directories.

**Comment by auscaster** [comment]
This has been fixed! You can also find precompiled libs here: https://sourcey.com/precompiled-webrtc-libraries/
