### ISSUE TITLE
...\sourcey\webrtc\include\webrtc/base/byteorder.h(111): error C3861: "htonll": not found

### ISSUE THREAD

**Issue by MaciekSyncro** [sourcey/libsourcey#188]
Hi,

any idea what I'm doing wrong. Compiing on a windows machine. Htonll is not defined.
I used the following CMAKE command:

cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_SHARED_LIBS=OFF -DBUILD_MODULES=ON -DBUILD_APPLICATIONS=ON -DBUILD_TESTS=OFF -DBUILD_SAMPLES=OFF -DBUILD_SAMPLES_webrtc=ON -DWITH_FFMPEG=ON -DWITH_WEBRTC=ON -DENABLE_LOGGING=ON -DBUILD_MODULE_base=ON -DBUILD_MODULE_av=ON -DBUILD_MODULE_crypto=ON -DBUILD_MODULE_http=ON -DBUILD_MODULE_json=ON -DBUILD_MODULE_net=ON -DBUILD_MODULE_socketio=ON -DBUILD_MODULE_symple=ON -DBUILD_MODULE_util=ON -DBUILD_MODULE_webrtc=ON -DFFMPEG_ROOT_DIR=C:\Google\ffmpeg -DWEBRTC_ROOT_DIR=C:\Google\sourcey\webrtc -DBUILD_WITH_STATIC_CRT=ON

Cheers,

Maciek

**Comment by tditsch** [comment]
Hi Maciek,

were you able to fix this? I get exactly the same error, could you please share your solution?

**Comment by MaciekSyncro** [comment]
Just comment the lines :-)

**Comment by Gongmeda** [comment]
try compiler preprocessor directive **#define INCL_EXTRA_HTON_FUNCTIONS**
