### ISSUE TITLE
Unable to build in windows 10

### ISSUE THREAD

**Issue by azmathmoosa** [sourcey/libsourcey#190]
Firstly, excellent work on the library!

In windows 10, I am able to build your library separately.  But when I try to build it along my project, it fails saying redifinition errors.

`C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\development\ds_library\utilities.hpp(146): warning C4018: '<': signed/unsigned mismatch [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\
development\mvp_ds_face\vs_build\exec.vcxproj]
C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\development\ds_library\utilities.hpp(148): warning C4018: '<': signed/unsigned mismatch [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\
development\mvp_ds_face\vs_build\exec.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(103): warning C4005: 'AF_IPX': macro redefinition [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\development\mvp_d
s_face\vs_build\exec.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock.h(457): note: see previous definition of 'AF_IPX'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(128): warning C4005: 'AF_MAX': macro redefinition [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\development\mvp_d
s_face\vs_build\exec.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock.h(476): note: see previous definition of 'AF_MAX'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(185): warning C4005: 'SO_DONTLINGER': macro redefinition [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\developmen
t\mvp_ds_face\vs_build\exec.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock.h(399): note: see previous definition of 'SO_DONTLINGER'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(235): error C2011: 'sockaddr': 'struct' type redefinition [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\developme
nt\mvp_ds_face\vs_build\exec.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock.h(1007): note: see declaration of 'sockaddr'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(437): error C2059: syntax error: 'constant' [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\development\mvp_ds_face
\vs_build\exec.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(491): error C2143: syntax error: missing ';' before '}' [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\development
\mvp_ds_face\vs_build\exec.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(491): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\Azmath\Documents\
DeepSight\deepsight\firmware\development\mvp_ds_face\vs_build\exec.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(572): warning C4005: 'IN_CLASSA': macro redefinition [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\development\mv
p_ds_face\vs_build\exec.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock.h(284): note: see previous definition of 'IN_CLASSA'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(578): warning C4005: 'IN_CLASSB': macro redefinition [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\development\mv
p_ds_face\vs_build\exec.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock.h(290): note: see previous definition of 'IN_CLASSB'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(584): warning C4005: 'IN_CLASSC': macro redefinition [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\development\mv
p_ds_face\vs_build\exec.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock.h(296): note: see previous definition of 'IN_CLASSC'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(595): warning C4005: 'INADDR_ANY': macro redefinition [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\development\m
vp_ds_face\vs_build\exec.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock.h(301): note: see previous definition of 'INADDR_ANY'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(597): warning C4005: 'INADDR_BROADCAST': macro redefinition [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\develop
ment\mvp_ds_face\vs_build\exec.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winsock.h(303): note: see previous definition of 'INADDR_BROADCAST'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\ws2def.h(633): error C2011: 'sockaddr_in': 'struct' type redefinition [C:\Users\Azmath\Documents\DeepSight\deepsight\firmware\develo
pment\mvp_ds_face\vs_build\exec.vcxproj]`

But all of it compiles fine in Ubuntu with gcc.  I googled a bit and some people suggested that there is a problem with the order in which `windows.h and winsock.h` are included but I don't know where/how to fix it!  It probably has something to do with libuv.  I am using `-DBUILD_DEPENDENCIES=ON`

Please help!

**Comment by auscaster** [comment]
Hi there, it's hard to comment exactly since I'm not sure how you're
including your headers, but make sure windows.h and winsock.h are included
before other headers, and only once.

**Comment by azmathmoosa** [comment]
I am trying to use libsourcey in my build system.  Basically I have the following directory tree 

```
-dependencies
--CMakeLists.txt
--libsourcey
---CMakeLists.txt
--another_lib
---CMakeLists.txt
-MainApp
--src
---CMakeLists.txt
```

In my dependency cmake file, I have used `ExternalProject_Add` to include the libraries. 

Then from my main app cmake file, I use `add_subdirectory(dependency)`

The net effect is that libsourcey is built and installed in a folder called `${CMAKE_BINARY_DIR}/deps_install` from which my app includes and links the libraries.

However, in windows 10, after the dependencies are built, it fails to build my app with the above error.

Can you suggest a better way to include the libsourcey cmake file into my main project?  I don't want to prebuild libsourcey.  I will be building my app on multiple platforms and architectures and want all the sources ready for build.  

Thanks.

**Comment by auscaster** [comment]
Sorry for not getting back to you sooner. There is a CMake solutionin the docs that lets you include and install LibSourcey intree with your current project: https://sourcey.com/libsourcey/getting-started/

```
cmake_minimum_required(VERSION 2.8.10)
project(exampleapp)

# Set the source directory and search locations as required for your project
set(sourcedir src)
set(sourcefiles ${sourcedir}/*.cpp)
set(headerfiles ${sourcedir}/*.h)

# Include LibSourcey
include("../libsourcey/LibSourcey.cmake")
include_directories(${Libourcey_INCLUDE_DIRS})

link_libraries(${LibSourcey_LIBRARIES})
include_directories(${sourcedir} ${LibSourcey_INCLUDE_DIRS})

# Glob your sources and headers
# Be sure to modify the search paths according to your project structure
file(GLOB_RECURSE sources ${sourcefiles})
file(GLOB_RECURSE headers ${headerfiles})

add_executable(exampleapp ${sources} ${headers})
install(TARGETS exampleapp)
```
