### ISSUE TITLE
 rtsp server example.

### ISSUE THREAD

**Issue by traw** [sourcey/libsourcey#192]
How to create example server which use rtsp protocol using libsourcey?

**Comment by traw** [comment]
I was looking through code, but it seems libsourcey doesn't support rtsp at the moment.

**Comment by auscaster** [comment]
Hi traw, you are correct in that rtsp is not supported. We use WebRTC for
streaming audio/video.

**Comment by traw** [comment]
Ok that's greats, I am developing media server.so thought libsourcey could be a very good option for that.

**Comment by traw** [comment]
Bust I think I can still develop based on this library based on webrtc and socketio.

**Comment by auscaster** [comment]
For a modern media app I would certainly recommend WebRTC over RTSP which
is a little dated these days.
Libsourcey + socketio + WebRTC make a great foundation for building a
modern video app.

**Comment by traw** [comment]
Thanks for great advice. I really appreciate that. But is  it possible to receive rtsp stream from remote server?

**Comment by auscaster** [comment]
I think WebRTC has some support, try ggogling it.

You can also integrate with Live555 for RTSP
