### ISSUE TITLE
Why one has to mark h264 stream for 'MP4' container?

### ISSUE THREAD

**Issue by sasmaster** [sourcey/libsourcey#196]
I am following h264 streaming tutorial.
And I see this:

```
options.oformat = av::Format{"MP4", "mp4",
    { "H.264", "libx264", 640, 480, 25, 48000, 128000, "yuv420p" },
    { "AAC", "aac", 2, 44100, 64000, "fltp" }};

```
Does that mean that every time I want to stream raw h264 it is going to be wrapped with mp4 container or anything like that? It doesn't make  sense for live video.

**Comment by auscaster** [comment]
h264 stream may be contained by a number of formats, not limited to mp4, so it is necessary to specify.
