### ISSUE TITLE
webrtcstreamer example error

### ISSUE THREAD

**Issue by rn3kk** [sourcey/libsourcey#199]
Hi!
I build libsourcey VS2015 with prebuild webrtc libs.  After started "node app" I see into browser web page.
But if i run webrtcstreamer c++ example application (from debug mode into VS2015), application is end work (0xC0000005: Access violation executing location 0x00000247B1DA69C0)
Bottom attached calll stack
`	WebRTC_Streamer.exe!scy::crypto::Hash::update(const void * data, unsigned __int64 length) Line 60	C++
 	WebRTC_Streamer.exe!scy::crypto::Hash::update(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & data) Line 67	C++
 	WebRTC_Streamer.exe!scy::http::ws::computeAccept(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & key) Line 369	C++
 	WebRTC_Streamer.exe!scy::http::ws::WebSocketFramer::completeClientHandshake(scy::http::Response & response) Line 605	C++
 	WebRTC_Streamer.exe!scy::http::ws::WebSocketFramer::checkClientHandshakeResponse(scy::http::Response & response) Line 405	C++
 	WebRTC_Streamer.exe!scy::http::ws::WebSocketAdapter::handleClientResponse(const scy::MutableBuffer & buffer, const scy::net::Address & peerAddr) Line 152	C++
 	WebRTC_Streamer.exe!scy::http::ws::WebSocketAdapter::onSocketRecv(scy::net::Socket & __formal, const scy::MutableBuffer & buffer, const scy::net::Address & peerAddress) Line 288	C++
 	WebRTC_Streamer.exe!scy::net::SocketAdapter::onSocketRecv(scy::net::Socket & socket, const scy::MutableBuffer & buffer, const scy::net::Address & peerAddress) Line 126	C++
 	WebRTC_Streamer.exe!scy::net::TCPSocket::onRecv(const scy::MutableBuffer & buf) Line 351	C++
 	WebRTC_Streamer.exe!scy::net::TCPSocket::onRead(const char * data, unsigned __int64 len) Line 345	C++
 	WebRTC_Streamer.exe!scy::Stream<uv_tcp_s>::handleRead(uv_stream_s * handle, __int64 nread, const uv_buf_t * buf) Line 162	C++
 	WebRTC_Streamer.exe!uv_process_tcp_read_req(uv_loop_s * loop, uv_tcp_s * handle, uv_req_s * req) Line 1029	C
 	WebRTC_Streamer.exe!uv_process_reqs(uv_loop_s * loop) Line 162	C
 	WebRTC_Streamer.exe!uv_run(uv_loop_s * loop, uv_run_mode mode) Line 496	C
`
May be this is throw from next function? 
`void Hash::update(const void* data, size_t length)
{
    internal::api(EVP_DigestUpdate(&_ctx, data, length));
}`

What am I doing wrong?

**Comment by auscaster** [comment]
Are you compiling with BoringSSL or OpenSSL? Perhaps there is a conflict with your SSL libraries?

**Comment by rn3kk** [comment]
Tnx, I solved this problem. I used lib webrtc-precompiled-builds instead webrtc-windows-builds. Where I change webrtc to webrtc-windows-builds, sample is rigth compile.
