### ISSUE TITLE
How to create simple SSL http server on libsourcey?

### ISSUE THREAD

**Issue by svmakarov** [sourcey/libsourcey#207]
I'm trying to create very simple SLL http server based on httpechoserver.h example.
I have two problems with this server:

1. Server returns reply string to client but it crash after that on following line: 
		conn->close();

2. Server crash when I try to access it by address without https (http://127.0.0.1:1337).

Could you please advice what I do wrong? What the right way to host SSL server?

Server code is following:

void raiseSSLEchoServer()
{
	net::SSLManager::initNoVerifyServer();
    http::Server srv(address, std::make_shared<net::SSLSocket>());
    srv.start();

    srv.Connection += [&](http::ServerConnection::Ptr conn)
    {
        std::string testReply = "Some Reply";
        conn->send(testReply .c_str(), testReply.length());
        conn->close();
    };

    waitForShutdown();
}

**Comment by auscaster** [comment]
At this point the SSL context needs to be passed to the Socket like so:

    net::SSLManager::initNoVerifyServer();

    http::Server srv(address, std::make_shared<net::SSLSocket>(
      net::SSLManager::instance().defaultServerContext()));
    srv.start();

    srv.Connection += [](http::ServerConnection::Ptr conn) {
        conn->send("hello universe", 14);
        conn->close();
    };

    std::cout << "HTTPS server listening on " << address << std::endl;
    waitForShutdown();

I would like to clean up the API in future a bit, but the Socket does not know if it's client or server side on instantiation so the context is necessary.

**Comment by vpiuro** [comment]
Hi,
I see, that if initNoVerifyServer() is called with default arguments (as here) , it reads private key and certificate from sources using SCY_SOURCE_DIR macro. Why it looks for the file inside sources, not e.g. in current directory. Thus, running the sample on another system without these sources fails. Besides, why top header libsourcey.h contains absolute paths for sources and build?
