### ISSUE TITLE
Some beginner's question

### ISSUE THREAD

**Issue by thuckechsu** [sourcey/libsourcey#208]
Hi, i'm working on a project that must use video streaming.

I have some questions:
- Does MSVC 2015 can compile your project? I saw this project featured C++14
- This project is for both server side and client side?

Thanks you for looking my issue.

**Comment by auscaster** [comment]
You can compile with VS2015 Version 3, and will probably use WebRTC. There
are a few samples that show how to use WebRTC on the client and server side
here: https://github.com/sourcey/libsourcey/tree/master/src/webrtc/samples

Fair warning though, WebRTC div is not easy for beginners!
