### ISSUE TITLE
Stream to WEBRtc from capture device

### ISSUE THREAD

**Issue by rn3kk** [sourcey/libsourcey#209]
Hello.
We need send stream from capture device to web page. What need for create this with using libsourcey library?

**Comment by auscaster** [comment]
You can achieve exactly that with the `webrtccapturer` sample!

**Comment by rn3kk** [comment]
Ok, I see it. 
But for capture device I see into input codec context codec is AV_CODEC_ID_RAWVIDEO. What should I do ? I need encode input raw frame using h264 codec and emit his? I don't have a output context, because have not  created output stream/file and don have muxing audio and video (need only video data).
