### ISSUE TITLE
Is it possible to capture live WebRTC video stream and transform it to RTMP stream using Libsourcey? 

### ISSUE THREAD

**Issue by MaksimDzhangirov** [sourcey/libsourcey#215]
I want to capture live WebRTC video stream and transform it to RTMP stream on server side. Is it possible using Libsourcey? If answer is yes, which example I should use as a starting point?

**Comment by auscaster** [comment]
We can do the WebRTC video capture part, but you would need to develop the
RTMP conversion code yourself. Check the `werrtctreamer` sample for
inspiration.

**Comment by MaksimDzhangirov** [comment]
FFMPEG can easy transform H.264/ACC stream to RTMP stream. In "WebRTC Native Video Streamer" demo you show how to stream realtime video to the the browser using LibSourcey and WebRTC. But I want to capture live WebRTC video stream from browser. In "WebRTC Native Video Recorder" can I set FFMPEG coding parameters like -preset, -tune, -r, -bufsize, output file extension, etc.?

**Comment by auscaster** [comment]
To capture the browser stream check `webrtcrecorder`, it captures a stream
from the browser, and records using FFmpeg on the server - I'm sure you can
modify that for your needs by modifying the recorder component.
