### ISSUE TITLE
Build problem on Mac: jsoncpp

### ISSUE THREAD

**Issue by ignacioavellino** [sourcey/libsourcey#55]
Hi!

I'm having some trouble building the code. Once I run

$ make

it stops at 17%

Console output:
[ 16%] Building C object deps/libuv/CMakeFiles/libuv.dir/src/unix/darwin-proctitle.c.o
Linking C shared library liblibuv.dylib
ld: warning: directory not found for option '-L/home/deploy/build/lib'
[ 16%] Built target libuv
Scanning dependencies of target jsoncpp
[ 17%] Building CXX object deps/jsoncpp/CMakeFiles/jsoncpp.dir/jsoncpp.cpp.o
Linking CXX shared library libjsoncpp.dylib
ld: warning: directory not found for option '-L/home/deploy/build/lib'
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [deps/jsoncpp/libjsoncpp.dylib] Error 1
make[1]: *** [deps/jsoncpp/CMakeFiles/jsoncpp.dir/all] Error 2
make: *** [all] Error 2

Apparently it fails to find a library when linking—libjsoncpp.dylib. So does this mean that it cannot build jsoncpp ..?

Sorry if this error seems too newbie!

—N

**Comment by sebastiansito** [comment]
Hi there,

u don't have librt on OS X and u don't need it. Search for "lrt" and remove it from link.txt in the dep that fails to link.

**Comment by ZelimDamian** [comment]
This does exactly what @sebastiansito suggested
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a1be73b..2430aed 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -202,7 +202,9 @@ if(MSVC)
   # CMAKE_CXX_STANDARD_LIBRARIES must be a string for MSVC
   set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} advapi32.lib iphlpapi.lib psapi.lib shell32.lib ws2_32.lib dsound.lib winmm.lib strmiids.lib")
 elseif(MSYS)
-  set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} -lws2_32 -liphlpapi") #${LibSourcey_INCLUDE_LIBRARIES} 
+  set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} -lws2_32 -liphlpapi") #${LibSourcey_INCLUDE_LIBRARIES}
+elseif(APPLE)
+    set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} -lm -lz -ldl") # -llibc -lglibc #${LibSourcey_INCLUDE_LIBRARIES}
 elseif(UNIX)
   set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} -lm -lz -ldl -lrt") # -llibc -lglibc #${LibSourcey_INCLUDE_LIBRARIES} 
 endif()
