### ISSUE TITLE
Issues with compiling samples on windows.

### ISSUE THREAD

**Issue by emujagic-devlogic** [sourcey/libsourcey#73]
I'm having issues compiling on windows.

I generate solution files and compile static libraries but when trying to compile samples I get bunch of unresolved references such as Logger and some more. Should I try to add all static libraries manually as linked libraries for samples ?

Should I generate libsourcey.dll from all modules and then link samples to that dll ?
If so, how do I generate one dll from multiple modules since it seems to me all modules are separate projects and I am not sure how to make on dll of all of them ?

Is there more info about compiling beside official page, or has anyone had issues with compiling on windows?
Maybe prebuilt binaries are available?

**Comment by auscaster** [comment]
It sounds like the dependencies and modules libs haven't been compiled yet hence they are unresolved, so try compiling the dependencies and modules first before the samples and applications.

More specifically disable BUILD_APPLICATIONS, BUILD_MODULE_SAMPLES and BUILD_MODULE_TESTS in cmake, then build libsourcey. This will create the shared libraries and dependencies. Next time round you can enable those options for building the binaries, and everything should work as expected.

**Comment by auscaster** [comment]
This issue is fixed by compiling and installing dependencies and modules before compiling any binaries:

    cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_DEPENDENCIES=ON -DBUILD_MODULES=ON -DBUILD_APPLICATIONS=OFF -DBUILD_MODULE_TESTS=OFF -DBUILD_MODULE_SAMPLES=OFF
    make
    sudo make install

Then compile your binaries now that deps are available:

    cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_APPLICATIONS=ON -DBUILD_MODULE_TESTS=ON -DBUILD_MODULE_SAMPLES=ON
    make
    sudo make install
