### ISSUE TITLE
lambda function error idler.cpp

### ISSUE THREAD

**Issue by marklendering** [sourcey/libsourcey#79]
During the generating project files step of libsourcey i get the following error: 
/work/libsourcey/src/base/src/idler.cpp: In lambda function:
/work/libsourcey/src/base/src/idler.cpp:75:22: error: 'this' was not captured for this lambda function

when looking for a solution i came accros this issue:
http://stackoverflow.com/questions/4940259/lambdas-require-capturing-this-to-call-static-member-function

trying this out i get the following error:
work/libsourcey/src/base/src/idler.cpp:82:3: error: cannot convert 'scy::Idler::startAsync()::<lambda(uv_idle_t*)>' to 'uv_idle_cb {aka void (*)(uv_idle_s*)}' for argument '2' to 'int uv_idle_start(uv_idle_t*, uv_idle_cb)'

**Comment by auscaster** [comment]
It looks like you're using an incompatible version of libuv, please use the libuv that comes with the source code.

**Comment by auscaster** [comment]
Closing this because of no response
