### ISSUE TITLE
More samples

### ISSUE THREAD

**Issue by ZelimDamian** [sourcey/libsourcey#81]
I started playing with libsourcey because of its video streaming potential (integration with mpeg + websockets etc). But the samples are very simplistic and give very little idea how to this. Could someone please point me in the right direction?

**Comment by auscaster** [comment]
There are a full range of samples that demonstrate streaming video over WebSocket, HTTP and TURN in the Symple module. The sample code is here: https://github.com/sourcey/libsourcey/tree/master/src/symple/samples/mediaserver
For the WebSocket responser check here: https://github.com/sourcey/libsourcey/blob/master/src/symple/samples/mediaserver/WebSocketResponder.h
If you want to use the `WebSocketResponder` without Symple, just pull `MediaServer::setupPacketStream(stream, options);` out into your own code - it's very straightforward to implement.
If you do decide to use Symple, the media player client can be used for testing, and can be found here: https://github.com/sourcey/symple-client

**Comment by auscaster** [comment]
@ZelimDamian I've made a number of updates to the media samples, please sync when you get a chance :)

**Comment by ZelimDamian** [comment]
Awesome! Thanks a lot. Will have a look shortly. This can probably be closed though.
