### ISSUE TITLE
Undefined reference to scy::av::AVPacketEncoder

### ISSUE THREAD

**Issue by Pic14kk** [sourcey/libsourcey#82]
in CMakeLists.txt:
`target_link_libraries(untitled2 ${Boost_LIBRARIES}
scy_base scy_crypto scy_net scy_http scy_media scy_util scy_archo scy_socketio scy_turn
${FFmpeg_LIBRARIES}
rtaudio  avcodec asound libuv crypto   http_parser
postproc  avdevice-ffmpeg
swscale avcodec-ffmpeg
avdevice avformat-ffmpeg
avutil avformat
avfilter
avcodec swscale-ffmpeg postproc-ffmpeg
postproc-ffmpeg    avutil-ffmpeg
avresample-ffmpeg swresample-ffmpeg avfilter-ffmpeg swresample
minizip z pthread)`

`MakeFiles/untitled2.dir/main.cpp.o: In function MPEGResponder::MPEGResponder(scy::http::ServerConnection&)':
/home/pwera/untiitled2/Newros/src/SourceyEx/CryptoEx.hpp:61: undefined reference to scy::av::AVPacketEncoder::AVPacketEncoder(scy::av::EncoderOptions const&, bool)'`
collect2: error: ld returned 1 exit status

When i copied all cmake modules (which comes from libsourcey folder) to 
`/usr/share/cmake-3.2/Modules`
and add 
`find_package(FFmpeg REQUIRED)` in CMakeLists.txt
i got `Error:Unknown CMake command "set_module_notfound".`

Sorry for my poor english :P

**Comment by auscaster** [comment]
Hmm ... I'm out today, are you able to submit a PR for this? It may be just a matter of including `scy/media/avpacketencoder.h` in the `MPEGResponder` file

**Comment by Pic14kk** [comment]
https://gist.github.com/Pic14kk/b4d61207df61254a0ce8

**Comment by auscaster** [comment]
Hey there, it looks like you're not including LibSourcey the right way, just add the following to your linker libraries: `scybase scyuv scymedia scyutil`, and add the libsourcey include directory, and you're good to go.

I'm going to close this one since it's not actually a bug.
