### ISSUE TITLE
Including compiled libsourcey in another project

### ISSUE THREAD

**Issue by MichalGallovic** [sourcey/libsourcey#84]
Hello,

pardon my newbieaness, but after compiling, how can I include libsourcey in another project ?
thankyou

**Comment by auscaster** [comment]
Hello again, which compiler are you using? The process will change a bit depending ....

Basically you need to
1) build libsourcey with cmake
2) include the compiled libraries you need into your project
3) include the libsourcey header locations into your project

**Comment by MichalGallovic** [comment]
I'm using gcc 4.8 compiler.

After building libsourcey *.so files were generated. Should I include them in the CMakeList alongside with header files ? If so, how can I do that ? 
I'm still struggling a bit to grasp the concept of cmake - when including libraries in the project, sometimes I can use keywords (i.e. with PCL library)

```
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
```

Are there such keywords available with libsourcey as well ? (sorry for so many questions )

**Comment by auscaster** [comment]
You're on the right track! 

Short answer no, the Sourcey symbols are not available in CMake for your external project, but you can include the libraries very easily.

After you so a `make install` of libsourcey you will see that the libscy_xxx.so files are copied into `/usr/local/lib`. 

Are you familiar with pkgconfig? You can use it directly or take a look at the `/usr/local/lib/pkgconfig/libsourcey.pc` for all the libsourcey libs and include directories. 

In order to include libsourcey with CMake you can just use something like:

```
include_directories(/usr/local/include /usr/local/share/scy/vendor/include)
link_directories(/usr/local/lib /usr/local/share/scy/vendor/lib)
target_link_libraries (${your_project_name} scy_base scy_archo scy_crypto scy_net scy_uv scy_http scy_json scy_media)
```

Hope that helps, just sing out if you need more help.

**Comment by auscaster** [comment]
Please sync with the latest repo before trying above code

**Comment by MichalGallovic** [comment]
I was not familiar with pkgconfig - very very helpful, thank you! There is one issue I'm unable to resolve. After writing cmake according to your hint, there is one more error:

```
/usr/local/include/scy/base.h:41:23: fatal error: scyconfig.h: No such file or directory
 #include "scyconfig.h"
```

when building libsourcey I can find scyconfig.h inside build folder. After make install, I am unable to find this header file in /usr/include/scy
Btw in` /usr/local/share/scy/vendor` I can only find the lib folder.

thank you for your help!

**Comment by auscaster** [comment]
I've just pushed a change that will include scyconfig.h in the install
target, so please pull the latest master and `make install` again.

Inside my `/usr/local/share/scy/vendor` I have three folders:
```
kam@sourcey:/usr/local/share/scy/vendor$ ls
include  lib  share
```

**Comment by MichalGallovic** [comment]
After reinstalling libsourcey, I still only have `lib` inside `/usr/local/share/scy/vendor`.
This is how my cmake looks like:
```
cmake_minimum_required(VERSION 3.3)
project(main)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

include_directories(/usr/local/include /usr/local/share/scy/vendor/include)
link_directories(/usr/local/lib /usr/local/share/scy/vendor/lib)


set(SOURCE_FILES main.cpp)
add_executable(main ${SOURCE_FILES})

target_link_libraries(
        main
        scy_base scy_http
)
```
When I try to include i.e. `#include <scy/http/url.h>`
 I get error
```
/usr/local/include/scy/http/url.h:26:25: fatal error: http_parser.h: No such file or directory
 #include <http_parser.h>
```
One thing to note - I installed libsourcey without OpenCV ( that is probably not the problem here though )

**Comment by auscaster** [comment]
Hi Michal

Sorry for the delay in getting back to you. I've made a quick patch to the build system, so please sync with the latest master and 'make install' again. Hopefully this fixes your issue!

**Comment by MichalGallovic** [comment]
thank you ! everything works now 👍

**Comment by auscaster** [comment]
Glad to hear it - hope you like the lib and just sing out if you have
questions.
