### ISSUE TITLE
Building on windows with visual studio 2015 and cmake-gui 3.5.2

### ISSUE THREAD

**Issue by denisps** [sourcey/libsourcey#88]
I'm trying to build it and here is what I'm getting:
http://pastebin.com/CJiWgz0L

It looks like it can't find scy_uv_094d.lib

**Comment by romanvolkov-io** [comment]
I've encountered exactly the same issue. There are no libs being created at all. The uv project consists of only one header file. Therefore, Visual Studio doesn't compile anything. If you create manually a dummy C++ file, which includes the header, the project doesn't compile due to errors.

**Comment by auscaster** [comment]
Hi @romanvolkov-io, thanks for your input. Can you please provide the compiler output with the errors you encountered?

**Comment by romanvolkov-io** [comment]
I've just rechecked it, fixed some include paths, and finally were able to compile it successfully. The CMake build setup is still very buggy, though.

See also: https://github.com/romanvolkov-io/libsourcey/commit/b3edfc1fde66d8c6d678aaf1eb71be7a202cd7c2

**Comment by surinkim** [comment]
Hello @auscaster and @romanvolkov-io,
I've got similar problem about uv project compile on windows.
 
By add include path and uvpp.cpp(just dummy file) to uv project, the problem has solved.
Can you check [this pull request](https://github.com/sourcey/libsourcey/pull/89/files)?

Thank you for your valuable time.

**Comment by auscaster** [comment]
Thanks for the PR, that will close this issue.

@romanvolkov-io if you have any further windows related fixes please feel free to submit a PR also.
