### ISSUE TITLE
request a webrtc exmaple  

### ISSUE THREAD

**Issue by notedit** [sourcey/libsourcey#93]
i want  to handle webrtc rtp package in server.

could you give some hint

**Comment by auscaster** [comment]
I'm currently working on a WebRTC demo for LibSourcey with Symple signaling but it's still a few days away yet.

Basically you can compile WebRTC with this project: https://github.com/sourcey/webrtcbuilds

Once compiled set `WEBRTC_INCLUDE_DIR` in cmake and you can then use any WebRTC classes inside your LibSourcey projects. Maybe check out the examples in the webrtc repo for a starting point.

**Comment by notedit** [comment]
ok  i  see your  demo,   i have build webrtc,  but does not figure out how to get the rtp data in server.

**Comment by auscaster** [comment]
This demo here shows how to implement WebRTC server side: https://github.com/sourcey/libsourcey/tree/master/src/symple/apps/webrtcstreamer
