### ISSUE TITLE
Can libsourcey(symple) get serveral outputs of  ffmepg and stream it through webRTC?

### ISSUE THREAD

**Issue by VinciShark** [sourcey/libsourcey#96]

**Comment by auscaster** [comment]
Yes there is a sample application that demonstrates something similar here: https://github.com/sourcey/libsourcey/tree/master/src/webrtc/apps/webrtcstreamer

It currently streams a live webcam source, but you can easily modify it to stream an FFmpeg source. If you require any custom functionality please contact me personally :)

**Comment by VinciShark** [comment]
@auscaster using tech in this article? http://sourcey.com/webrtc-custom-opencv-video-capture/

**Comment by auscaster** [comment]
That article is a little dated now, please just use the demo code for reference.

**Comment by VinciShark** [comment]
Thanks! If have any problem, connect by what would you prefer, Github, Twitter, or Email?
We now working on streaming & producting tools for TV stations.

**Comment by auscaster** [comment]
Email would be best: auscaster@gmail.com
