### ISSUE TITLE
Build success, but error occur when running examples.

### ISSUE THREAD

**Issue by VinciShark** [sourcey/libsourcey#98]
![image](https://cloud.githubusercontent.com/assets/9538504/19419716/f63dcc32-940f-11e6-92b7-c5cd9eb21f71.png)

**Comment by auscaster** [comment]
Please make sure the location of your ffmpeg dll files are in the system
PATH.

Later when you go to release your application you will need to package them
with the executable so others can run your application.

**Comment by VinciShark** [comment]
I fix that. Windows need download two version of ffmpeg and add both to system path.

- ffmpeg-win64-dev
- ffmpeg-win64-shared
