### ISSUE TITLE
Sample\deviceenumeratord.exe return wrong result

### ISSUE THREAD

**Issue by VinciShark** [sourcey/libsourcey#99]
Deviceenumeratord logs that I have no video capture devices.
![image](https://cloud.githubusercontent.com/assets/9538504/19425110/715ce85c-9461-11e6-9646-ffc7bd71055f.png)

But actually I have one.
![image](https://cloud.githubusercontent.com/assets/9538504/19425116/796f9d14-9461-11e6-96d1-23482aefb846.png)

**Comment by VinciShark** [comment]
![image](https://cloud.githubusercontent.com/assets/9538504/19427582/7d53d344-9477-11e6-9deb-675e4b438641.png)

**Comment by auscaster** [comment]
Hmm, for some reason FFmpeg and DirectShow is not enumerating your devices.

Can you run the following command on your system and let me know what the
output is: `ffmpeg -list_devices true -f dshow -i dummy`

More info here: https://trac.ffmpeg.org/wiki/DirectShow

**Comment by VinciShark** [comment]
> C:\Users\Vinci>ffmpeg -list_devices true -f dshow -i dummy
> ffmpeg version 3.1.4 Copyright (c) 2000-2016 the FFmpeg developers
>   built with gcc 5.4.0 (GCC)
>   configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
>   libavutil      55. 28.100 / 55. 28.100
>   libavcodec     57. 48.101 / 57. 48.101
>   libavformat    57. 41.100 / 57. 41.100
>   libavdevice    57.  0.101 / 57.  0.101
>   libavfilter     6. 47.100 /  6. 47.100
>   libswscale      4.  1.100 /  4.  1.100
>   libswresample   2.  1.100 /  2.  1.100
>   libpostproc    54.  0.100 / 54.  0.100
> [dshow @ 00000000007672a0] DirectShow video devices (some may be both video and audio devices)
> [dshow @ 00000000007672a0]  "PC Camera"
> [dshow @ 00000000007672a0]     Alternative name "@device_pnp_\\?\usb#vid_058f&pid_3881&mi_00#7&2bbc027d&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global"
> [dshow @ 00000000007672a0]  "XSplitBroadcaster"
> [dshow @ 00000000007672a0]     Alternative name "@device_sw_{860BB310-5D01-11D0-BD3B-00A0C911CE86}\{VHSplitProc}_XSplitBroadcaster_1_staticsource_VIDEO"
> [dshow @ 00000000007672a0] DirectShow audio devices
> [dshow @ 00000000007672a0]  "楹﹀厠椋?(High Definition Audio 璁惧)"
> [dshow @ 00000000007672a0]     Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{7CBF73E0-8C9B-422E-A4C2-8360FB8B28F1}"
> [dshow @ 00000000007672a0]  "XSplitBroadcaster"
> [dshow @ 00000000007672a0]     Alternative name "@device_sw_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\{VHSplitProc}_XSplitBroadcaster_1_staticsource_AUDIO"
> dummy: Immediate exit requested
> 
> C:\Users\Vinci>
>

**Comment by VinciShark** [comment]
ffmpge can, but libsourcey failed?

**Comment by auscaster** [comment]
I've updated the output in deviceenumeratord.exe, can you please sync with latest master and show me the output?

**Comment by auscaster** [comment]
@VinciShark if you have skype you can add me: auscaster

**Comment by auscaster** [comment]
Can you please tell me if HAVE_FFMPEG_AVDEVICE defined in `build/libsourcey.h` ?

**Comment by VinciShark** [comment]
please wait a minute, my skype need reinstall

**Comment by VinciShark** [comment]
![image](https://cloud.githubusercontent.com/assets/9538504/19436091/d18abbf2-94a0-11e6-993d-a1d84eb4a32f.png)

**Comment by auscaster** [comment]
OK thanks, please sync and let me know the new output from deviceenumeratord.exe
